# Generated by Django 5.2.13 on 2026-05-15 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CandidateBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bundle_key", models.CharField(max_length=160)),
                ("generation_index", models.PositiveIntegerField(blank=True, null=True)),
                ("extractor_coord", models.JSONField()),
                ("output_direction", models.CharField(max_length=20)),
                ("output_stub_coord", models.JSONField()),
                ("extension_pattern_key", models.CharField(blank=True, max_length=120)),
                ("extension_coords_json", models.JSONField(blank=True, default=list)),
                ("transport_kind", models.CharField(max_length=40)),
                ("placement_state", models.CharField(default="provisional", max_length=60)),
                ("local_score", models.FloatField(default=0)),
                ("fitness_json", models.JSONField(blank=True, default=dict)),
                ("reject_reason", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ("solver_run", "bundle_key"),
            },
        ),
        migrations.CreateModel(
            name="AsteroidProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(fields=["slug"], name="asteroid_la_slug_399592_idx"),
                    models.Index(fields=["-updated_at"], name="asteroid_la_updated_3b7b31_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AsteroidMapInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("copy_code", "Copy code"),
                            ("decoded_json", "Decoded JSON"),
                            ("import_file", "Import file"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("copy_code", models.TextField(blank=True)),
                ("decoded_json", models.JSONField(blank=True, default=dict)),
                ("content_sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_inputs",
                        to="asteroid_lab.asteroidproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PatternTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("template_key", models.CharField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("pattern_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("template_key",),
                "indexes": [
                    models.Index(fields=["template_key"], name="asteroid_la_templat_faed84_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PatternVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("variant_key", models.CharField(max_length=160)),
                ("rotation_quarter_turns", models.PositiveSmallIntegerField(default=0)),
                ("mirrored", models.BooleanField(default=False)),
                ("transport_kind", models.CharField(default="default", max_length=40)),
                ("variant_json", models.JSONField(blank=True, default=dict)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="asteroid_lab.patterntemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("template", "variant_key"),
            },
        ),
        migrations.CreateModel(
            name="ReplayTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("track_key", models.CharField(max_length=160)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replay_tracks",
                        to="asteroid_lab.asteroidproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ReplayFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("frame_index", models.PositiveIntegerField()),
                ("frame_key", models.CharField(max_length=120)),
                ("phase", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("frame_payload", models.JSONField(blank=True, default=dict)),
                ("cell_overlay_json", models.JSONField(blank=True, default=dict)),
                ("metric_snapshot_json", models.JSONField(blank=True, default=dict)),
                ("is_placeholder", models.BooleanField(default=False)),
                ("is_keyframe", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replay_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="asteroid_lab.replaytrack",
                    ),
                ),
            ],
            options={
                "ordering": ("replay_track", "frame_index"),
            },
        ),
        migrations.CreateModel(
            name="RoutingProbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("probe_kind", models.CharField(default="fast_feasibility", max_length=80)),
                ("start_stub_coord", models.JSONField()),
                ("goal_summary_json", models.JSONField(blank=True, default=dict)),
                ("reachable", models.BooleanField(default=False)),
                ("path_cost", models.FloatField(blank=True, null=True)),
                ("path_cells_json", models.JSONField(blank=True, default=list)),
                ("failure_reason", models.CharField(blank=True, max_length=120)),
                ("explored_count", models.PositiveIntegerField(default=0)),
                (
                    "candidate_bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_probes",
                        to="asteroid_lab.candidatebundle",
                    ),
                ),
            ],
            options={
                "ordering": ("candidate_bundle", "id"),
            },
        ),
        migrations.CreateModel(
            name="SolverRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_key", models.CharField(db_index=True, max_length=120)),
                ("algorithm_label", models.CharField(default="ga_hybrid", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("config_json", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solver_runs",
                        to="asteroid_lab.asteroidproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SolverMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("frame_index", models.PositiveIntegerField()),
                ("phase", models.CharField(blank=True, max_length=80)),
                ("fitness_components_json", models.JSONField(blank=True, default=dict)),
                ("aggregate_score", models.FloatField(blank=True, null=True)),
                ("throughput_hint", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "solver_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="asteroid_lab.solverrun",
                    ),
                ),
            ],
            options={
                "ordering": ("solver_run", "frame_index"),
            },
        ),
        migrations.AddField(
            model_name="replaytrack",
            name="solver_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replay_tracks",
                to="asteroid_lab.solverrun",
            ),
        ),
        migrations.AddField(
            model_name="candidatebundle",
            name="solver_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_bundles",
                to="asteroid_lab.solverrun",
            ),
        ),
        migrations.CreateModel(
            name="TopologyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rule_key", models.CharField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("short_label", models.CharField(max_length=80)),
                ("rule_group", models.CharField(max_length=80)),
                ("severity", models.CharField(default="info", max_length=40)),
                ("description", models.TextField(blank=True)),
                ("examples_json", models.JSONField(blank=True, default=list)),
                ("diagram_json", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("sort_order", "rule_key"),
                "indexes": [
                    models.Index(
                        fields=["rule_group", "is_active", "sort_order"],
                        name="asteroid_la_rule_gr_ce123d_idx",
                    ),
                    models.Index(fields=["rule_key"], name="asteroid_la_rule_ke_d9308a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TopologyRuleModalContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("modal_title", models.CharField(blank=True, max_length=200)),
                ("lead_html", models.TextField(blank=True)),
                ("sections_json", models.JSONField(blank=True, default=list)),
                ("footer_json", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modal_content",
                        to="asteroid_lab.topologyrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UIPlaybackSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("current_frame_index", models.PositiveIntegerField(default=0)),
                ("is_playing", models.BooleanField(default=False)),
                ("playback_speed_ms", models.PositiveIntegerField(default=800)),
                ("selected_layer", models.CharField(default="combined", max_length=80)),
                ("selected_candidate_id", models.CharField(blank=True, max_length=120)),
                ("selected_bundle_id", models.CharField(blank=True, max_length=120)),
                ("ui_state_json", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replay_track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_session",
                        to="asteroid_lab.replaytrack",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsteroidCellSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("layer", models.CharField(default="combined", max_length=80)),
                ("cell_grid_json", models.JSONField(blank=True, default=dict)),
                ("overlay_json", models.JSONField(blank=True, default=dict)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "map_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_snapshots",
                        to="asteroid_lab.asteroidmapinput",
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at",),
                "indexes": [
                    models.Index(
                        fields=["map_input", "layer"], name="asteroid_la_map_inp_bef2b5_idx"
                    ),
                    models.Index(
                        fields=["map_input", "-captured_at"], name="asteroid_la_map_inp_e08366_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="asteroidmapinput",
            index=models.Index(
                fields=["project", "source_kind"], name="asteroid_la_project_700a1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asteroidmapinput",
            index=models.Index(fields=["content_sha256"], name="asteroid_la_content_51ae38_idx"),
        ),
        migrations.AddIndex(
            model_name="patternvariant",
            index=models.Index(
                fields=["template", "variant_key"], name="asteroid_la_templat_c375f2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="patternvariant",
            constraint=models.UniqueConstraint(
                fields=("template", "variant_key"), name="uniq_al_pattern_variant_per_template"
            ),
        ),
        migrations.AddIndex(
            model_name="replayframe",
            index=models.Index(
                fields=["replay_track", "frame_index"], name="asteroid_la_replay__f35620_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="replayframe",
            index=models.Index(
                fields=["replay_track", "is_keyframe"], name="asteroid_la_replay__b9b87e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="replayframe",
            constraint=models.UniqueConstraint(
                fields=("replay_track", "frame_index"), name="uniq_replay_frame_index_per_track"
            ),
        ),
        migrations.AddIndex(
            model_name="routingprobe",
            index=models.Index(
                fields=["candidate_bundle", "probe_kind"], name="asteroid_la_candida_48abcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routingprobe",
            index=models.Index(
                fields=["candidate_bundle", "reachable"], name="asteroid_la_candida_b688dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solverrun",
            index=models.Index(fields=["project", "status"], name="asteroid_la_project_6c2639_idx"),
        ),
        migrations.AddIndex(
            model_name="solverrun",
            index=models.Index(
                fields=["project", "-created_at"], name="asteroid_la_project_9e12dd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="solverrun",
            constraint=models.UniqueConstraint(
                fields=("project", "run_key"), name="uniq_al_solver_run_key_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="solvermetricsnapshot",
            index=models.Index(
                fields=["solver_run", "frame_index"], name="asteroid_la_solver__3da633_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="solvermetricsnapshot",
            constraint=models.UniqueConstraint(
                fields=("solver_run", "frame_index"), name="uniq_al_metric_snapshot_frame"
            ),
        ),
        migrations.AddIndex(
            model_name="replaytrack",
            index=models.Index(
                fields=["project", "track_key"], name="asteroid_la_project_6a6dba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="replaytrack",
            constraint=models.UniqueConstraint(
                fields=("project", "track_key"), name="uniq_replay_track_key_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatebundle",
            index=models.Index(
                fields=["solver_run", "generation_index"], name="asteroid_la_solver__b0c2d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatebundle",
            index=models.Index(
                fields=["solver_run", "placement_state"], name="asteroid_la_solver__0e834c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatebundle",
            constraint=models.UniqueConstraint(
                fields=("solver_run", "bundle_key"), name="uniq_al_candidate_bundle_key_per_run"
            ),
        ),
        migrations.AddIndex(
            model_name="topologyrulemodalcontent",
            index=models.Index(fields=["rule"], name="asteroid_la_rule_id_79f1bf_idx"),
        ),
        migrations.AddIndex(
            model_name="uiplaybacksession",
            index=models.Index(fields=["replay_track"], name="asteroid_la_replay__7e6ca2_idx"),
        ),
        migrations.AddIndex(
            model_name="uiplaybacksession",
            index=models.Index(fields=["-updated_at"], name="asteroid_la_updated_2935af_idx"),
        ),
    ]
