# Generated by Django 5.2.13 on 2026-05-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asteroid_lab", "0002_asteroid_map_input_layout_fingerprints"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneticSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, verbose_name="이름")),
                ("code", models.TextField(verbose_name="복사 문자열")),
                (
                    "decoded_json",
                    models.JSONField(blank=True, default=dict, verbose_name="디코드 JSON"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="genetic_samples",
                        to="asteroid_lab.asteroidproject",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "유전자 샘플",
                "verbose_name_plural": "유전자 샘플",
                "ordering": ("-updated_at",),
                "indexes": [
                    models.Index(fields=["-updated_at"], name="asteroid_la_updated_2f809f_idx"),
                    models.Index(
                        fields=["project", "-updated_at"], name="asteroid_la_project_83c4dc_idx"
                    ),
                ],
            },
        ),
    ]
