# Generated by Django 5.2.13 on 2026-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asteroid_lab", "0003_genetic_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="geneticsample",
            name="gene_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="전수 생성 샘플의 정본 식별자(update_or_create 기준). 수동 샘플은 비움.",
                max_length=256,
                null=True,
                verbose_name="gene 키",
            ),
        ),
        migrations.AddField(
            model_name="geneticsample",
            name="metadata_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="예: generator 버전, transport_kind, topology 요약(게임 JSON과 분리).",
                verbose_name="메타데이터",
            ),
        ),
        migrations.AddConstraint(
            model_name="geneticsample",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gene_key__isnull", False)),
                fields=("gene_key",),
                name="uniq_genetic_sample_gene_key_when_set",
            ),
        ),
    ]
