# Generated by Django 5.2.13 on 2026-05-18 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asteroid_lab", "0004_genetic_sample_gene_key_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconstructedAsteroidMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_key", models.CharField(db_index=True, max_length=120)),
                ("copy_code", models.TextField(verbose_name="복사 문자열 (SHAPEZ2-4-…$)")),
                (
                    "decoded_json",
                    models.JSONField(blank=True, default=dict, verbose_name="디코드 JSON"),
                ),
                (
                    "summary_json",
                    models.JSONField(blank=True, default=dict, verbose_name="reconstruction 요약"),
                ),
                ("cell_count", models.PositiveIntegerField(default=0)),
                ("layout_fingerprint", models.CharField(blank=True, db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "map_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconstructed_maps",
                        to="asteroid_lab.asteroidmapinput",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconstructed_maps",
                        to="asteroid_lab.asteroidproject",
                    ),
                ),
                (
                    "solver_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconstructed_maps",
                        to="asteroid_lab.solverrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "복원 소행성 맵",
                "verbose_name_plural": "복원 소행성 맵",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["map_input", "-created_at"], name="asteroid_la_map_inp_4ed005_idx"
                    ),
                    models.Index(
                        fields=["project", "-created_at"], name="asteroid_la_project_ef5909_idx"
                    ),
                    models.Index(
                        fields=["layout_fingerprint"], name="asteroid_la_layout__1955f4_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("map_input", "run_key"),
                        name="uniq_reconstructed_map_per_map_input_run_key",
                    )
                ],
            },
        ),
    ]
