# Generated by Django 5.2.13 on 2026-05-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asteroid_lab", "0005_reconstructed_asteroid_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="anchor_raw_x",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="anchor_raw_y",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="coord_system",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="export_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="게임 export JSON"),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="original_copy_code",
            field=models.TextField(blank=True, verbose_name="원본 paste copy"),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="rebuilt_copy_code",
            field=models.TextField(blank=True, verbose_name="export_json 인코딩"),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="reconstruction_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="복원 셀 메타"),
        ),
        migrations.AlterField(
            model_name="reconstructedasteroidmap",
            name="copy_code",
            field=models.TextField(verbose_name="복사 문자열 (SHAPEZ2-4-…$, = rebuilt)"),
        ),
        migrations.AlterField(
            model_name="reconstructedasteroidmap",
            name="decoded_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="디코드 JSON (lab)"),
        ),
        migrations.CreateModel(
            name="ReconstructedAsteroidEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("raw_x", models.IntegerField(blank=True, null=True)),
                ("raw_y", models.IntegerField(blank=True, null=True)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("t", models.IntegerField(blank=True, null=True, verbose_name="numeric T")),
                ("layout_id", models.CharField(blank=True, max_length=128)),
                ("layout_name", models.CharField(blank=True, max_length=128)),
                ("r", models.IntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("miner", "Miner"),
                            ("miner_extension", "Miner extension"),
                            ("belt", "Belt"),
                            ("pipe", "Pipe"),
                            ("asteroid_field", "Asteroid field"),
                            ("void", "Void"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("cleanup_removed", "Cleanup removed"),
                            ("reconstruction", "Reconstruction"),
                            ("generated", "Generated"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="asteroid_lab.reconstructedasteroidmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "복원 소행성 엔트리",
                "verbose_name_plural": "복원 소행성 엔트리",
                "indexes": [
                    models.Index(fields=["map", "x", "y"], name="asteroid_la_map_id_b0a570_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("map", "x", "y", "kind", "source"),
                        name="uniq_recon_entry_map_xy_kind_source",
                    )
                ],
            },
        ),
    ]
