# Generated by Django 5.2.13 on 2026-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asteroid_lab", "0007_map_input_reconstructed_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asteroidmapinput",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.RemoveIndex(
            model_name="reconstructedasteroidmap",
            name="asteroid_la_map_inp_4ed005_idx",
        ),
        migrations.RemoveIndex(
            model_name="reconstructedasteroidmap",
            name="asteroid_la_project_ef5909_idx",
        ),
        migrations.RenameIndex(
            model_name="asteroidmapinput",
            new_name="asteroid_la_updated_012fe4_idx",
            old_name="asteroid_la_mapinp_upd_idx",
        ),
        migrations.RenameIndex(
            model_name="reconstructedasteroidmap",
            new_name="asteroid_la_updated_ad8205_idx",
            old_name="asteroid_la_recon_upd_idx",
        ),
        migrations.AddIndex(
            model_name="reconstructedasteroidmap",
            index=models.Index(
                fields=["map_input", "-updated_at"], name="asteroid_la_map_inp_b1dcee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reconstructedasteroidmap",
            index=models.Index(
                fields=["project", "-updated_at"], name="asteroid_la_project_e2d099_idx"
            ),
        ),
    ]
