# Generated by Django 5.2.13 on 2026-05-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asteroid_lab", "0008_alter_asteroidmapinput_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReconstructedAsteroidEntry",
        ),
        migrations.RemoveIndex(
            model_name="reconstructedasteroidmap",
            name="asteroid_la_layout__1955f4_idx",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="anchor_raw_x",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="anchor_raw_y",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="anchor_server_x",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="anchor_server_y",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="cell_count",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="coord_system",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="export_json",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="layout_fingerprint",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="rebuilt_copy_code",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="reconstruction_json",
        ),
        migrations.RemoveField(
            model_name="reconstructedasteroidmap",
            name="summary_json",
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="original_decoded_json",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="원본 디코드 JSON (persist 시점 스냅샷)"
            ),
        ),
        migrations.AlterField(
            model_name="reconstructedasteroidmap",
            name="copy_code",
            field=models.TextField(blank=True, verbose_name="full_map lab copy (SHAPEZ2-4-…$)"),
        ),
        migrations.AlterField(
            model_name="reconstructedasteroidmap",
            name="decoded_json",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="full_map lab 디코드 JSON"
            ),
        ),
    ]
