# Generated by Django 5.2.13 on 2026-05-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asteroid_lab", "0011_island_extractor_blueprint"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="islandextractorblueprint",
            new_name="asteroid_la_carrier_cdd133_idx",
            old_name="asteroid_la_carrier_0c8f2a_idx",
        ),
    ]
