# Generated by Django 5.2.13 on 2026-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "asteroid_lab",
            "0012_rename_asteroid_la_carrier_0c8f2a_idx_asteroid_la_carrier_cdd133_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="admin_list_thumbnail",
            field=models.ImageField(
                blank=True,
                upload_to="reconstructed_maps/list/%Y/%m/",
                verbose_name="Admin changelist thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="admin_list_thumbnail_cell_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="admin_list_thumbnail_grid_h",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="admin_list_thumbnail_grid_w",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="admin_list_thumbnail_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="admin_list_thumbnail_renderer_version",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="reconstructedasteroidmap",
            name="admin_list_thumbnail_truncated",
            field=models.BooleanField(default=False),
        ),
    ]
