# Generated by Django 6.0.5 on 2026-05-31 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asteroid_lab", "0018_rename_geneticsample_geneseed"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="geneseed",
            new_name="asteroid_la_updated_66c3ec_idx",
            old_name="asteroid_la_updated_2f809f_idx",
        ),
        migrations.RenameIndex(
            model_name="geneseed",
            new_name="asteroid_la_project_f64091_idx",
            old_name="asteroid_la_project_83c4dc_idx",
        ),
        migrations.AlterField(
            model_name="geneseed",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gene_seeds",
                to="asteroid_lab.asteroidproject",
                verbose_name="프로젝트",
            ),
        ),
    ]
