"""
Domain types: coordinates, enums, DTOs, and grid conventions.

No I/O, no Django, no v1 solver imports. Algorithm behaviour belongs in ``steps``/feature
packages (decode, placement, …), not here.
"""

from django_apps.shapez_asteroid.services.asteroid_mining_layout_v2.domain.coord import (
    BBox,
    BlueprintCell,
    Coord,
    as_blueprint_cell,
)
from django_apps.shapez_asteroid.services.asteroid_mining_layout_v2.domain.dto import (
    DecodedExistingLayoutContext,
    DuplicateCoordSampleDTO,
    EquipmentTransportAttachment,
    ExistingEquipmentAnalysis,
    ExistingLayoutAnalysis,
    ExistingLayoutIssue,
    ExistingLayoutSolverHints,
    ExistingTransportAnalysis,
    ExtensionPlacement,
    ExtractorPlacement,
    FinalValidationReport,
    GridMask,
    MetricsSnapshot,
    OutputStub,
    Pass1Result,
    Pass2Result,
    PlacementBundle,
    PlacementId,
    ReconstructionDiagnosisDTO,
    ReconstructionDTO,
    ReconstructionResult,
    RoutePath,
    RoutingFailure,
    RoutingResult,
    RoutingStateSnapshot,
    SolverRunContext,
    SolverRunLimits,
    Step4RoutingResult,
    TraceEvent,
    TransportComponentSummary,
    TrunkLoadSummary,
)
from django_apps.shapez_asteroid.services.asteroid_mining_layout_v2.domain.enums import (
    CommitReason,
    EquipmentKind,
    ExistingLayoutIssueCode,
    ExistingLayoutIssueSeverity,
    MineableEmptyCause,
    PlacementCommitState,
    RecoveryTrigger,
    RejectedReason,
    RollbackReason,
    RouteZone,
    SolverTerminationTier,
    SourceKind,
    TransportComponentStatus,
    TransportKind,
)
from django_apps.shapez_asteroid.services.asteroid_mining_layout_v2.placement.placement_fsm import (
    apply_pass1_provisional_commits,
    apply_pass2_provisional_commits,
    assert_all_provisional_commits,
    assert_no_routed_confirmed,
    assert_placement_commit_transition,
    assert_provisionally_placed,
    is_terminal_state,
    placement_commit_transition_allowed,
)

from .decoded_blueprint import DecodedBlueprintDocument

__all__ = [
    "BBox",
    "BlueprintCell",
    "CommitReason",
    "Coord",
    "assert_placement_commit_transition",
    "assert_provisionally_placed",
    "apply_pass1_provisional_commits",
    "apply_pass2_provisional_commits",
    "assert_all_provisional_commits",
    "assert_no_routed_confirmed",
    "DecodedBlueprintDocument",
    "DecodedExistingLayoutContext",
    "DuplicateCoordSampleDTO",
    "EquipmentKind",
    "EquipmentTransportAttachment",
    "ExistingEquipmentAnalysis",
    "ExistingLayoutAnalysis",
    "ExistingLayoutIssue",
    "ExistingLayoutIssueCode",
    "ExistingLayoutIssueSeverity",
    "ExistingLayoutSolverHints",
    "ExistingTransportAnalysis",
    "ExtensionPlacement",
    "ExtractorPlacement",
    "FinalValidationReport",
    "GridMask",
    "MineableEmptyCause",
    "MetricsSnapshot",
    "OutputStub",
    "Pass1Result",
    "Pass2Result",
    "PlacementBundle",
    "PlacementCommitState",
    "placement_commit_transition_allowed",
    "PlacementId",
    "ReconstructionDTO",
    "ReconstructionDiagnosisDTO",
    "ReconstructionResult",
    "RecoveryTrigger",
    "RejectedReason",
    "RollbackReason",
    "RoutePath",
    "RouteZone",
    "RoutingFailure",
    "RoutingResult",
    "RoutingStateSnapshot",
    "SolverRunContext",
    "SolverRunLimits",
    "SolverTerminationTier",
    "SourceKind",
    "is_terminal_state",
    "Step4RoutingResult",
    "TraceEvent",
    "TransportComponentStatus",
    "TransportComponentSummary",
    "TransportKind",
    "TrunkLoadSummary",
    "as_blueprint_cell",
]
