"""
Domain types: coordinates, enums, DTOs, and grid conventions.

No I/O, no Django, no v1 solver imports. Algorithm behaviour belongs in ``steps``/feature
packages (decode, placement, …), not here.
"""

from django_apps.shapez_asteroid.services.asteroid_mining_layout_v2.domain.coord import (
    BBox,
    BlueprintCell,
    Coord,
    as_blueprint_cell,
)
from django_apps.shapez_asteroid.services.asteroid_mining_layout_v2.domain.dto import (
    DecodedBlueprintDocument,
    DecodedExistingLayoutContext,
    EquipmentTransportAttachment,
    ExistingEquipmentAnalysis,
    ExistingLayoutAnalysis,
    ExistingLayoutIssue,
    ExistingLayoutSolverHints,
    ExistingTransportAnalysis,
    ExtensionPlacement,
    ExtractorPlacement,
    FinalValidationReport,
    GridMask,
    MetricsSnapshot,
    OutputStub,
    Pass1Result,
    Pass2Result,
    PlacementBundle,
    PlacementId,
    ReconstructionDTO,
    RoutePath,
    RoutingFailure,
    RoutingResult,
    RoutingStateSnapshot,
    SolverRunContext,
    SolverRunLimits,
    Step4RoutingResult,
    TraceEvent,
    TransportComponentSummary,
    TrunkLoadSummary,
)
from django_apps.shapez_asteroid.services.asteroid_mining_layout_v2.domain.enums import (
    CommitReason,
    EquipmentKind,
    ExistingLayoutIssueCode,
    ExistingLayoutIssueSeverity,
    PlacementCommitState,
    RecoveryTrigger,
    RejectedReason,
    RollbackReason,
    RouteZone,
    SolverTerminationTier,
    SourceKind,
    TransportComponentStatus,
    TransportKind,
)

__all__ = [
    "BBox",
    "BlueprintCell",
    "CommitReason",
    "Coord",
    "DecodedBlueprintDocument",
    "DecodedExistingLayoutContext",
    "EquipmentKind",
    "EquipmentTransportAttachment",
    "ExistingEquipmentAnalysis",
    "ExistingLayoutAnalysis",
    "ExistingLayoutIssue",
    "ExistingLayoutIssueCode",
    "ExistingLayoutIssueSeverity",
    "ExistingLayoutSolverHints",
    "ExistingTransportAnalysis",
    "ExtensionPlacement",
    "ExtractorPlacement",
    "FinalValidationReport",
    "GridMask",
    "MetricsSnapshot",
    "OutputStub",
    "Pass1Result",
    "Pass2Result",
    "PlacementBundle",
    "PlacementCommitState",
    "PlacementId",
    "ReconstructionDTO",
    "RecoveryTrigger",
    "RejectedReason",
    "RollbackReason",
    "RoutePath",
    "RouteZone",
    "RoutingFailure",
    "RoutingResult",
    "RoutingStateSnapshot",
    "SolverRunContext",
    "SolverRunLimits",
    "SolverTerminationTier",
    "SourceKind",
    "Step4RoutingResult",
    "TraceEvent",
    "TransportComponentStatus",
    "TransportComponentSummary",
    "TransportKind",
    "TrunkLoadSummary",
    "as_blueprint_cell",
]
