# Generated by Django 5.2.13 on 2026-05-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphPreviewImage",
            fields=[
                ("cache_key", models.CharField(max_length=24, primary_key=True, serialize=False)),
                ("png", models.BinaryField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "web_graph_preview_image",
            },
        ),
    ]
