# Generated by Django 5.2.13 on 2026-05-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial_graph_preview_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShapePartSprite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sprite_key", models.CharField(max_length=192, unique=True)),
                ("mesh_key", models.CharField(max_length=64)),
                ("color_code", models.CharField(blank=True, max_length=16)),
                ("material_key", models.CharField(blank=True, max_length=64)),
                ("quadrant_index", models.PositiveSmallIntegerField()),
                ("image", models.ImageField(upload_to="shape_part_sprites/")),
                ("image_width", models.PositiveSmallIntegerField()),
                ("image_height", models.PositiveSmallIntegerField()),
                ("renderer_version", models.CharField(default="v1", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "web_shape_part_sprite",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "mesh_key",
                            "color_code",
                            "material_key",
                            "quadrant_index",
                            "renderer_version",
                        ),
                        name="uniq_shape_part_sprite_variant",
                    )
                ],
            },
        ),
    ]
