# Generated by Django 5.2.13 on 2026-05-06 18:00

from django.db import migrations, models

import django_apps.web.shape_part_sprite_storage


def forwards_copy_sprite_assets(apps, schema_editor):
    """Copy PNGs from MEDIA_ROOT/shape_part_sprites to static web/assets and fix DB paths."""
    import os
    import shutil
    from pathlib import Path

    from django.conf import settings

    assets_prefix = "assets/shape_part_sprites/"
    SpriteModel = apps.get_model("web", "ShapePartSprite")
    media_root = Path(settings.MEDIA_ROOT)
    dest_root = Path(settings.SHAPE_PART_SPRITE_STATIC_ROOT)

    for row in SpriteModel.objects.values("pk", "image"):
        old_rel = row["image"] or ""
        if not old_rel or old_rel.startswith(assets_prefix):
            continue
        if not str(old_rel).startswith("shape_part_sprites/"):
            continue
        src = media_root / str(old_rel)
        if not src.is_file():
            continue
        new_rel = assets_prefix + Path(str(old_rel)).name
        dest = dest_root / new_rel.replace("/", os.sep)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        SpriteModel.objects.filter(pk=row["pk"]).update(image=new_rel)


def noop_reverse_shape_part_assets(apps, schema_editor):
    """Moving baked PNGs back under MEDIA is optional; keep reverse as no-op."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_shape_part_sprite"),
    ]

    operations = [
        migrations.RunPython(forwards_copy_sprite_assets, noop_reverse_shape_part_assets),
        migrations.AlterField(
            model_name="shapepartsprite",
            name="image",
            field=models.ImageField(
                storage=django_apps.web.shape_part_sprite_storage.shape_part_sprite_storage,
                upload_to="assets/shape_part_sprites/",
            ),
        ),
    ]
