# Generated by Django 5.2.13 on 2026-05-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_shape_part_sprite_assets"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsteroidDecodedLayoutDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content_sha256", models.CharField(db_index=True, max_length=64, unique=True)),
                ("source_label", models.CharField(blank=True, max_length=512)),
                ("root_v", models.PositiveIntegerField()),
                ("bp_type", models.CharField(blank=True, max_length=64)),
                ("binary_version", models.PositiveIntegerField(blank=True, null=True)),
                ("icon_json", models.JSONField(blank=True, null=True)),
                ("document_json", models.JSONField()),
                ("entry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "web_asteroid_decoded_layout_document",
            },
        ),
        migrations.CreateModel(
            name="AsteroidDecodedLayoutEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entry_index", models.PositiveIntegerField()),
                ("entry_json", models.JSONField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="web.asteroiddecodedlayoutdocument",
                    ),
                ),
            ],
            options={
                "db_table": "web_asteroid_decoded_layout_entry",
                "ordering": ("entry_index",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "entry_index"),
                        name="uniq_asteroid_decoded_layout_entry_index",
                    )
                ],
            },
        ),
    ]
