"""Shim: relocated to shapez2_factory.application.asteroid_lab.layers.contracts.layer_slugs."""

from __future__ import annotations

from shapez2_factory.application.asteroid_lab.layers.contracts.layer_slugs import (
    LAYER_01_RECONSTRUCTION,
    LAYER_02_EXTERIOR_TRANSPORT,
    LAYER_03_RIM_GREEDY_PLACEMENT,
    LAYER_03_RIM_MINING_BUNDLES,
    LAYER_04_INNER_PATTERN_FILL,
    LAYER_04_RIM_BUNDLE_PLACEMENT,
    LAYER_05_COMMIT_VALIDATE,
    LAYER_05_INNER_PATTERN_FILL,
    LAYER_06_COMMIT_VALIDATE,
    LAYERS_02_TO_05,
    LAYERS_02_TO_06,
    LAYERS_02_TO_06_ACTIVE,
)

__all__ = [
    "LAYER_01_RECONSTRUCTION",
    "LAYER_02_EXTERIOR_TRANSPORT",
    "LAYER_03_RIM_GREEDY_PLACEMENT",
    "LAYER_03_RIM_MINING_BUNDLES",
    "LAYER_04_INNER_PATTERN_FILL",
    "LAYER_04_RIM_BUNDLE_PLACEMENT",
    "LAYER_05_COMMIT_VALIDATE",
    "LAYER_05_INNER_PATTERN_FILL",
    "LAYER_06_COMMIT_VALIDATE",
    "LAYERS_02_TO_05",
    "LAYERS_02_TO_06",
    "LAYERS_02_TO_06_ACTIVE",
]
