"""Stable ``SolverRun.config_json`` keys (wire contract; no free-form strings)."""

from __future__ import annotations

SOLVER_RUN_CONFIG_GENE_TEMPLATE_SOURCE_KEY = "gene_template_source"
SOLVER_RUN_CONFIG_SERVER_XY_PARAMS_KEY = "server_xy_params"
SOLVER_RUN_CONFIG_SOLVER_SUMMARY_KEY = "solver_summary"
SOLVER_RUN_CONFIG_RUNTIME_REPLAY_FRAMES_KEY = "solver_runtime_replay_frames"
SOLVER_RUN_CONFIG_MAX_CANDIDATES_KEY = "max_candidates"
SOLVER_RUN_CONFIG_ROUTE_PROBE_MAX_EXPANSIONS_KEY = "route_probe_max_expansions"
SOLVER_RUN_CONFIG_PROBE_BUDGET_FACTOR_KEY = "probe_budget_factor"
SOLVER_RUN_CONFIG_MINERS_PER_ROUTE_OUT_KEY = "miners_per_route_out"
SOLVER_RUN_CONFIG_GAME_DATA_SNAPSHOT_META_KEY = "game_data_snapshot_meta"

__all__ = [
    "SOLVER_RUN_CONFIG_GAME_DATA_SNAPSHOT_META_KEY",
    "SOLVER_RUN_CONFIG_GENE_TEMPLATE_SOURCE_KEY",
    "SOLVER_RUN_CONFIG_MAX_CANDIDATES_KEY",
    "SOLVER_RUN_CONFIG_MINERS_PER_ROUTE_OUT_KEY",
    "SOLVER_RUN_CONFIG_PROBE_BUDGET_FACTOR_KEY",
    "SOLVER_RUN_CONFIG_ROUTE_PROBE_MAX_EXPANSIONS_KEY",
    "SOLVER_RUN_CONFIG_RUNTIME_REPLAY_FRAMES_KEY",
    "SOLVER_RUN_CONFIG_SERVER_XY_PARAMS_KEY",
    "SOLVER_RUN_CONFIG_SOLVER_SUMMARY_KEY",
]
