"""Stable ``SolverRun.config_json`` keys (wire contract; no free-form strings)."""

from __future__ import annotations

SOLVER_RUN_CONFIG_GENE_TEMPLATE_SOURCE_KEY = "gene_template_source"
SOLVER_RUN_CONFIG_SERVER_XY_PARAMS_KEY = "server_xy_params"
SOLVER_RUN_CONFIG_SOLVER_SUMMARY_KEY = "solver_summary"
SOLVER_RUN_CONFIG_RUNTIME_REPLAY_FRAMES_KEY = "solver_runtime_replay_frames"
SOLVER_RUN_CONFIG_MAX_CANDIDATES_KEY = "max_candidates"
SOLVER_RUN_CONFIG_ROUTE_PROBE_MAX_EXPANSIONS_KEY = "route_probe_max_expansions"
SOLVER_RUN_CONFIG_PROBE_BUDGET_FACTOR_KEY = "probe_budget_factor"
SOLVER_RUN_CONFIG_MINERS_PER_ROUTE_OUT_KEY = "miners_per_route_out"
SOLVER_RUN_CONFIG_GAME_DATA_SNAPSHOT_META_KEY = "game_data_snapshot_meta"
SOLVER_RUN_CONFIG_SELECTION_COMMIT_ORDER_STRATEGY_KEY = "selection_commit_order_strategy"
SOLVER_RUN_CONFIG_COMMIT_ORDER_BEAM_WIDTH_KEY = "commit_order_beam_width"
SOLVER_RUN_CONFIG_SELECTION_SHADOW_POLICY_KEY = "selection_shadow_policy"
SOLVER_RUN_CONFIG_COMMIT_ORDER_POLICY_KEY = "commit_order_policy"
SOLVER_RUN_CONFIG_MODE_KEY = "mode"
SOLVER_RUN_CONFIG_RUNTIME_BUDGET_MS_KEY = "runtime_budget_ms"
SOLVER_RUN_CONFIG_CANDIDATE_BUDGET_MS_KEY = "candidate_budget_ms"
SOLVER_RUN_CONFIG_COMMIT_BUDGET_MS_KEY = "commit_budget_ms"
SOLVER_RUN_CONFIG_VALIDATION_BUDGET_MS_KEY = "validation_budget_ms"
SOLVER_RUN_CONFIG_RUNTIME_BEAM_WIDTH_KEY = "runtime_beam_width"
SOLVER_RUN_CONFIG_MAX_CANDIDATES_RUNTIME_KEY = "max_candidates_runtime"
SOLVER_RUN_CONFIG_MAX_PROBE_EXPANSIONS_RUNTIME_KEY = "max_probe_expansions_runtime"
SOLVER_RUN_CONFIG_MAX_COMMIT_ATTEMPTS_RUNTIME_KEY = "max_commit_attempts_runtime"
SOLVER_RUN_CONFIG_MAX_SELECTED_VARIANTS_PER_EXTRACTOR_KEY = (
    "max_selected_variants_per_extractor"
)

__all__ = [
    "SOLVER_RUN_CONFIG_GAME_DATA_SNAPSHOT_META_KEY",
    "SOLVER_RUN_CONFIG_GENE_TEMPLATE_SOURCE_KEY",
    "SOLVER_RUN_CONFIG_MAX_CANDIDATES_KEY",
    "SOLVER_RUN_CONFIG_MINERS_PER_ROUTE_OUT_KEY",
    "SOLVER_RUN_CONFIG_PROBE_BUDGET_FACTOR_KEY",
    "SOLVER_RUN_CONFIG_ROUTE_PROBE_MAX_EXPANSIONS_KEY",
    "SOLVER_RUN_CONFIG_RUNTIME_REPLAY_FRAMES_KEY",
    "SOLVER_RUN_CONFIG_CANDIDATE_BUDGET_MS_KEY",
    "SOLVER_RUN_CONFIG_COMMIT_BUDGET_MS_KEY",
    "SOLVER_RUN_CONFIG_COMMIT_ORDER_BEAM_WIDTH_KEY",
    "SOLVER_RUN_CONFIG_COMMIT_ORDER_POLICY_KEY",
    "SOLVER_RUN_CONFIG_MAX_CANDIDATES_RUNTIME_KEY",
    "SOLVER_RUN_CONFIG_MAX_COMMIT_ATTEMPTS_RUNTIME_KEY",
    "SOLVER_RUN_CONFIG_MAX_PROBE_EXPANSIONS_RUNTIME_KEY",
    "SOLVER_RUN_CONFIG_MODE_KEY",
    "SOLVER_RUN_CONFIG_RUNTIME_BEAM_WIDTH_KEY",
    "SOLVER_RUN_CONFIG_RUNTIME_BUDGET_MS_KEY",
    "SOLVER_RUN_CONFIG_VALIDATION_BUDGET_MS_KEY",
    "SOLVER_RUN_CONFIG_MAX_SELECTED_VARIANTS_PER_EXTRACTOR_KEY",
    "SOLVER_RUN_CONFIG_SELECTION_COMMIT_ORDER_STRATEGY_KEY",
    "SOLVER_RUN_CONFIG_SELECTION_SHADOW_POLICY_KEY",
    "SOLVER_RUN_CONFIG_SERVER_XY_PARAMS_KEY",
    "SOLVER_RUN_CONFIG_SOLVER_SUMMARY_KEY",
]
