"""Stable ``SolverRun.config_json`` keys (wire contract; no free-form strings)."""

from __future__ import annotations

SOLVER_RUN_CONFIG_GENE_TEMPLATE_SOURCE_KEY = "gene_template_source"
SOLVER_RUN_CONFIG_SOLVER_SUMMARY_KEY = "solver_summary"
SOLVER_RUN_CONFIG_RUNTIME_REPLAY_FRAMES_KEY = "solver_runtime_replay_frames"
SOLVER_RUN_CONFIG_GAME_DATA_SNAPSHOT_META_KEY = "game_data_snapshot_meta"  # legacy; do not write

SOLVER_RUN_CONFIG_GAME_DATA_SNAPSHOT_PROVENANCE_KEY = "game_data_snapshot_provenance"
SOLVER_RUN_CONFIG_RTTP_RECORD_REPLAY_KEY = "rttp_record_replay"
SOLVER_RUN_CONFIG_RTTP_MACRO_ONLY_MODE_KEY = "macro_only_mode"
SOLVER_RUN_CONFIG_RTTP_MAX_MACRO_CANDIDATES_KEY = "max_macro_candidates"

__all__ = [
    "SOLVER_RUN_CONFIG_GAME_DATA_SNAPSHOT_META_KEY",
    "SOLVER_RUN_CONFIG_GAME_DATA_SNAPSHOT_PROVENANCE_KEY",
    "SOLVER_RUN_CONFIG_RTTP_MACRO_ONLY_MODE_KEY",
    "SOLVER_RUN_CONFIG_RTTP_MAX_MACRO_CANDIDATES_KEY",
    "SOLVER_RUN_CONFIG_RTTP_RECORD_REPLAY_KEY",
    "SOLVER_RUN_CONFIG_GENE_TEMPLATE_SOURCE_KEY",
    "SOLVER_RUN_CONFIG_RUNTIME_REPLAY_FRAMES_KEY",
    "SOLVER_RUN_CONFIG_SOLVER_SUMMARY_KEY",
]
