"""Stable tokens for RTTP core recovery stage diagnosis (output-only)."""

from __future__ import annotations

# Pipeline-ordered stage ids (recovery A1; S3 = route/FOT materialization track).
STAGE_S1_RECONSTRUCTION = "S1"
STAGE_S2_EXTENSION_GEOMETRY = "S2"
STAGE_S3_ROUTE_MATERIALIZATION = "S3"
STAGE_S4_PLACEMENT_GOAL = "S4"
STAGE_S5_SELECTION = "S5"
STAGE_S6_COMMIT_VALIDATION_GAP = "S6"
STAGE_S7_MATERIALIZATION = "S7"
STAGE_S8_VALIDATION = "S8"

STAGE_ORDER: tuple[str, ...] = (
    STAGE_S1_RECONSTRUCTION,
    STAGE_S2_EXTENSION_GEOMETRY,
    STAGE_S3_ROUTE_MATERIALIZATION,
    STAGE_S4_PLACEMENT_GOAL,
    STAGE_S5_SELECTION,
    STAGE_S6_COMMIT_VALIDATION_GAP,
    STAGE_S7_MATERIALIZATION,
    STAGE_S8_VALIDATION,
)

FLAG_NO_COMMITTED_EXTRACTORS = "no_committed_extractors"
FLAG_RECONSTRUCTION_ENVELOPE_VACUOUS = "reconstruction_envelope_vacuous"
FLAG_MISSING_EXTENSIONS = "missing_extensions"
FLAG_ROUTE_MATERIALIZATION_MISSING = "route_materialization_missing"
FLAG_OUTPUT_TRANSPORT_MISSING = "output_transport_missing"
FLAG_EXTERIOR_ROUTE_MISSING = "exterior_route_missing"
FLAG_VALIDATION_FALSE_POSITIVE = "validation_false_positive"
FLAG_VALIDATION_FAILED = "validation_failed"
FLAG_CANDIDATE_POOL_EMPTY = "candidate_pool_empty"
FLAG_PLACEMENT_GOAL_SHORTFALL = "placement_goal_shortfall"

SYMPTOM_ROUTE_ZERO_VALIDATION_PASSED = "route_cells_zero_but_validation_passed"
SYMPTOM_NO_COMMITS = "no_committed_extractors"
SYMPTOM_NONE = "none"

__all__ = [
    "FLAG_CANDIDATE_POOL_EMPTY",
    "FLAG_EXTERIOR_ROUTE_MISSING",
    "FLAG_MISSING_EXTENSIONS",
    "FLAG_NO_COMMITTED_EXTRACTORS",
    "FLAG_OUTPUT_TRANSPORT_MISSING",
    "FLAG_PLACEMENT_GOAL_SHORTFALL",
    "FLAG_RECONSTRUCTION_ENVELOPE_VACUOUS",
    "FLAG_ROUTE_MATERIALIZATION_MISSING",
    "FLAG_VALIDATION_FAILED",
    "FLAG_VALIDATION_FALSE_POSITIVE",
    "STAGE_ORDER",
    "STAGE_S1_RECONSTRUCTION",
    "STAGE_S2_EXTENSION_GEOMETRY",
    "STAGE_S3_ROUTE_MATERIALIZATION",
    "STAGE_S4_PLACEMENT_GOAL",
    "STAGE_S5_SELECTION",
    "STAGE_S6_COMMIT_VALIDATION_GAP",
    "STAGE_S7_MATERIALIZATION",
    "STAGE_S8_VALIDATION",
    "SYMPTOM_NO_COMMITS",
    "SYMPTOM_NONE",
    "SYMPTOM_ROUTE_ZERO_VALIDATION_PASSED",
]
