# Generated by Django 5.2.13 on 2026-05-18 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShapezBasedataRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("game_version", models.PositiveIntegerField(db_index=True, unique=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("document_count", models.PositiveIntegerField(default=0)),
                (
                    "integrity_status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("schema_checked", "Schema checked"),
                            ("xref_checked", "Cross-ref checked"),
                            ("semantic_checked", "Semantic checked"),
                            ("sealed", "Sealed"),
                            ("failed", "Failed"),
                        ],
                        default="imported",
                        max_length=32,
                    ),
                ),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                ("release_integrity_hash", models.CharField(blank=True, max_length=64)),
                ("seal_algorithm", models.CharField(default="shapez-ivvd-seal-v1", max_length=64)),
                ("seal_input_canonical_json", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-game_version",),
            },
        ),
        migrations.CreateModel(
            name="ShapezBasedataDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("identifiers", "identifiers.json"),
                            ("buildings", "buildings.json"),
                            ("translations", "translations"),
                            ("scenario", "scenario"),
                            ("difficulty_preset", "difficulty preset"),
                            ("scenario_parameter_preset", "scenario parameter preset"),
                            ("json_schema", "json schema"),
                            ("version", "version file"),
                            ("other", "other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("logical_key", models.CharField(blank=True, default="", max_length=200)),
                ("source_relative_path", models.CharField(max_length=500)),
                ("byte_size", models.BigIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("raw_text", models.TextField(blank=True)),
                ("compressed_raw_blob", models.BinaryField(blank=True, null=True)),
                ("raw_compression_codec", models.CharField(blank=True, max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("schema_valid", models.BooleanField(blank=True, null=True)),
                ("schema_validation_errors", models.JSONField(blank=True, default=list)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("schema_version", models.CharField(blank=True, max_length=200)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="shapez_core.shapezbasedatarelease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShapezCanonicalArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("artifact_type", models.CharField(db_index=True, max_length=80)),
                ("derivation_step", models.CharField(blank=True, max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_artifacts",
                        to="shapez_core.shapezcanonicalartifact",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_artifacts",
                        to="shapez_core.shapezbasedatarelease",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_artifacts",
                        to="shapez_core.shapezbasedatadocument",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ShapezGameIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category", models.CharField(db_index=True, max_length=120)),
                ("value", models.CharField(db_index=True, max_length=512)),
                ("normalized_value", models.CharField(blank=True, db_index=True, max_length=512)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_identifiers",
                        to="shapez_core.shapezbasedatarelease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShapezValidationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("validation_phase", models.CharField(db_index=True, max_length=40)),
                ("success", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                ("validator_version", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_runs",
                        to="shapez_core.shapezbasedatarelease",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ShapezIntegrityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("error", "Error"), ("warning", "Warning")],
                        default="error",
                        max_length=16,
                    ),
                ),
                ("issue_code", models.CharField(db_index=True, max_length=80)),
                ("json_path", models.CharField(blank=True, max_length=500)),
                ("message", models.TextField()),
                ("related_identifier", models.CharField(blank=True, db_index=True, max_length=512)),
                ("is_superseded", models.BooleanField(db_index=True, default=False)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrity_issues",
                        to="shapez_core.shapezbasedatadocument",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_issues",
                        to="shapez_core.shapezbasedatarelease",
                    ),
                ),
                (
                    "superseded_by_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="shapez_core.shapezvalidationrun",
                    ),
                ),
                (
                    "validation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="shapez_core.shapezvalidationrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-validation_run_id", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="shapezbasedatadocument",
            index=models.Index(fields=["release", "kind"], name="shapez_core_release_91bb6e_idx"),
        ),
        migrations.AddIndex(
            model_name="shapezbasedatadocument",
            index=models.Index(
                fields=["release", "source_relative_path"], name="shapez_core_release_a8a893_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shapezbasedatadocument",
            constraint=models.UniqueConstraint(
                fields=("release", "kind", "logical_key"),
                name="shapez_basedata_document_release_kind_logical_key_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="shapezgameidentifier",
            index=models.Index(
                fields=["release", "category"], name="shapez_core_release_32f5d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shapezgameidentifier",
            index=models.Index(fields=["release", "value"], name="shapez_core_release_a79706_idx"),
        ),
        migrations.AddConstraint(
            model_name="shapezgameidentifier",
            constraint=models.UniqueConstraint(
                fields=("release", "category", "value"),
                name="shapez_game_identifier_release_category_value_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="shapezvalidationrun",
            index=models.Index(
                fields=["release", "validation_phase", "-created_at"],
                name="shapez_core_release_487bf7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shapezintegrityissue",
            index=models.Index(
                fields=["release", "issue_code"], name="shapez_core_release_001925_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shapezintegrityissue",
            index=models.Index(
                fields=["release", "is_superseded"], name="shapez_core_release_3421fd_idx"
            ),
        ),
    ]
