# Generated by Django 5.2.13 on 2026-05-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shapez_core", "0002_ivvd_lookups_and_fks"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shapezbasedatadocument",
            new_name="shapez_core_release_5a6951_idx",
            old_name="shapez_core_doc_release_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="shapezgameidentifier",
            new_name="shapez_core_release_b8ba4d_idx",
            old_name="shapez_core_gid_release_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="shapezintegrityissue",
            new_name="shapez_core_release_9012d5_idx",
            old_name="shapez_core_issue_release_type_idx",
        ),
        migrations.RenameIndex(
            model_name="shapezvalidationrun",
            new_name="shapez_core_release_450ce0_idx",
            old_name="shapez_core_release_487bf7_idx",
        ),
    ]
