# Generated by Django — shapez2Solver

from django.db import migrations, models


def _backfill_sprite_paths(apps, schema_editor) -> None:  # noqa: ARG001
    ShapezGameIdentifier = apps.get_model("shapez_core", "ShapezGameIdentifier")
    from django_apps.shapez_core.lab_sprite_path import resolve_sprite_static_relpath

    batch: list = []
    for gid in ShapezGameIdentifier.objects.iterator(chunk_size=500):
        rel = resolve_sprite_static_relpath(gid.value)
        if gid.sprite_static_relpath != rel:
            gid.sprite_static_relpath = rel
            batch.append(gid)
        if len(batch) >= 500:
            ShapezGameIdentifier.objects.bulk_update(batch, ["sprite_static_relpath"])
            batch.clear()
    if batch:
        ShapezGameIdentifier.objects.bulk_update(batch, ["sprite_static_relpath"])


def _clear_sprite_paths(apps, schema_editor) -> None:  # noqa: ARG001
    ShapezGameIdentifier = apps.get_model("shapez_core", "ShapezGameIdentifier")
    ShapezGameIdentifier.objects.all().update(sprite_static_relpath="")


class Migration(migrations.Migration):
    dependencies = [
        (
            "shapez_core",
            "0003_rename_shapez_core_doc_release_kind_idx_shapez_core_release_5a6951_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shapezgameidentifier",
            name="sprite_static_relpath",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Static path under web/assets/sprites/ (posix), if a lab SVG exists.",
                max_length=280,
            ),
        ),
        migrations.RunPython(_backfill_sprite_paths, _clear_sprite_paths),
    ]
