"""Appendix-only historical anchors for P1-ELCP-RF-C0 (NOT primary evidence)."""

from __future__ import annotations

# P1-ELCP-RF RF.1 / A2 (frozen reports — reference only)
HISTORICAL_GREEDY_REGRET_COMMIT_ORDER_LEN = 59
HISTORICAL_PRIMARY_COMMITTED_COUNT = 3
HISTORICAL_PRIMARY_REPROBE_FAILED_COUNT = 29

# B1 Gate A overlap-pack target_floor (reference only)
HISTORICAL_OVERLAP_PACK_COMMIT_ORDER_LEN = 67

__all__ = [
    "HISTORICAL_GREEDY_REGRET_COMMIT_ORDER_LEN",
    "HISTORICAL_OVERLAP_PACK_COMMIT_ORDER_LEN",
    "HISTORICAL_PRIMARY_COMMITTED_COUNT",
    "HISTORICAL_PRIMARY_REPROBE_FAILED_COUNT",
]
