# Generated by Django 5.2.13 on 2026-05-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("group_key", models.CharField(max_length=255, unique=True)),
                ("registry_stable_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "display_profile",
                    models.CharField(
                        choices=[
                            ("plain", "buildings.json"),
                            ("lazy_overlay", "building_groups.json"),
                        ],
                        max_length=16,
                    ),
                ),
                ("display_name_key", models.CharField(blank=True, default="", max_length=512)),
                ("is_transport_building", models.BooleanField(default=False)),
                ("placement_mode", models.CharField(blank=True, default="", max_length=64)),
                ("player_buildable", models.BooleanField(default=True)),
                ("selectable", models.BooleanField(default=True)),
                ("removable", models.BooleanField(default=True)),
                ("auto_connect", models.BooleanField(default=False)),
                ("source_row_index", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["group_key"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("batch_name", models.CharField(blank=True, default="", max_length=128)),
                ("manifest_self_hash", models.CharField(max_length=80, unique=True)),
                ("game_version", models.CharField(max_length=128)),
                ("unity_version", models.CharField(max_length=64)),
                ("dump_mod_version", models.CharField(max_length=32)),
                ("dump_schema_version", models.CharField(max_length=32)),
                ("dump_timestamp_utc", models.DateTimeField()),
                ("source_method", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="ShapeComponentKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("component_key", models.CharField(max_length=128, unique=True)),
                ("catalog_shape_code", models.CharField(blank=True, default="", max_length=8)),
                ("display_label", models.CharField(blank=True, default="", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="BuildingLocalizationOverlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title_key", models.CharField(blank=True, default="", max_length=512)),
                ("description_key", models.CharField(blank=True, default="", max_length=512)),
                ("lazy_text_namespace", models.CharField(blank=True, default="", max_length=64)),
                (
                    "building_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localization",
                        to="game_data.buildinggroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuildingSimulationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_transport_building", models.BooleanField(default=False)),
                ("pipette_override_id", models.CharField(blank=True, default="", max_length=128)),
                ("show_stat_belt_processing_time", models.BooleanField(default=False)),
                ("show_stat_buildings_per_full_belt", models.BooleanField(default=False)),
                ("show_in_speed_overview", models.BooleanField(default=False)),
                (
                    "building_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_setting",
                        to="game_data.buildinggroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameContentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                (
                    "content_kind",
                    models.CharField(
                        choices=[
                            ("prefab", "Prefab"),
                            ("sprite", "Sprite"),
                            ("material", "Material"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_stable_id", models.CharField(max_length=64)),
                ("content_path", models.CharField(max_length=512)),
                ("logical_path", models.CharField(blank=True, default="", max_length=512)),
                ("display_name_key", models.CharField(blank=True, default="", max_length=512)),
                ("dump_source_type", models.CharField(blank=True, default="", max_length=128)),
                ("unity_source_guid", models.CharField(blank=True, default="", max_length=64)),
                ("source_row_index", models.PositiveIntegerField()),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_assets",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FluidColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("color_name", models.CharField(max_length=64, unique=True)),
                ("fluid_kind", models.CharField(default="ColorFluid", max_length=32)),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                ("source_row_index", models.PositiveIntegerField()),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fluid_colors",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("warning_index", models.PositiveIntegerField()),
                ("message", models.TextField()),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to="game_data.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["warning_index"],
            },
        ),
        migrations.CreateModel(
            name="ExportIncompleteSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("section_code", models.CharField(max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomplete_sections",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClrTypeRegistryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("type_name", models.CharField(max_length=512)),
                ("assembly_name", models.CharField(max_length=512)),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                ("is_compiler_generated", models.BooleanField(default=False)),
                ("source_row_index", models.PositiveIntegerField()),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clr_types",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuildingVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("internal_name", models.CharField(max_length=255, unique=True)),
                ("source_stable_id", models.CharField(max_length=64)),
                ("display_name_key", models.CharField(blank=True, default="", max_length=512)),
                ("is_mirrored", models.BooleanField(default=False)),
                ("size_x", models.SmallIntegerField(default=0)),
                ("size_y", models.SmallIntegerField(default=0)),
                ("size_z", models.SmallIntegerField(default=0)),
                ("connector_count", models.PositiveSmallIntegerField(default=0)),
                ("source_row_index", models.PositiveIntegerField()),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_variants",
                        to="game_data.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["internal_name"],
            },
        ),
        migrations.AddField(
            model_name="buildinggroup",
            name="import_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_groups",
                to="game_data.importbatch",
            ),
        ),
        migrations.CreateModel(
            name="AssetMetaReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("meta_stable_id", models.CharField(max_length=64, unique=True)),
                ("logical_path", models.CharField(max_length=512, unique=True)),
                ("display_name_key", models.CharField(blank=True, default="", max_length=512)),
                ("source_row_index", models.PositiveIntegerField()),
                (
                    "content_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meta_links",
                        to="game_data.gamecontentasset",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_references",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtifactChecksum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("artifact_filename", models.CharField(max_length=128)),
                ("expected_sha256", models.CharField(max_length=80)),
                ("import_status", models.CharField(default="pending", max_length=32)),
                ("is_incomplete", models.BooleanField(default=False)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checksums",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalizationExportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_empty", models.BooleanField(default=True)),
                ("is_incomplete", models.BooleanField(default=False)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("expected_hash", models.CharField(blank=True, default="", max_length=80)),
                (
                    "import_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localization_status",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocalizedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("message_key", models.CharField(max_length=512)),
                ("locale_code", models.CharField(default="en", max_length=16)),
                ("message_text", models.TextField()),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localized_messages",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchGlobalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("config_key", models.CharField(default="default", max_length=64)),
                ("config_value", models.TextField(blank=True, default="")),
                (
                    "import_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_config",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchMechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("mechanic_key", models.CharField(max_length=255, unique=True)),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_mechanics",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("node_key", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("icon_id", models.CharField(blank=True, default="", max_length=128)),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_milestones",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchSideQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("node_key", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_side_quests",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchSideUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("node_key", models.CharField(max_length=255, unique=True)),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_side_upgrades",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("upgrade_key", models.CharField(max_length=255, unique=True)),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_upgrades",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("parent_kind", models.CharField(max_length=16)),
                ("parent_key", models.CharField(max_length=255)),
                (
                    "required_mechanic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="game_data.researchmechanic",
                    ),
                ),
                (
                    "required_upgrade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="game_data.researchupgrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalBeltSpeedPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("base_speed", models.CharField(blank=True, default="", max_length=64)),
                ("steps_per_tick", models.PositiveIntegerField(default=0)),
                (
                    "import_batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belt_speed_policy",
                        to="game_data.importbatch",
                    ),
                ),
                (
                    "research_upgrade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="belt_policies",
                        to="game_data.researchupgrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShapeRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("operation_uid", models.PositiveIntegerField(unique=True)),
                ("shape_hash", models.CharField(max_length=128, unique=True)),
                ("quadrant_count", models.PositiveSmallIntegerField(default=4)),
                ("layer_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "catalog_source",
                    models.CharField(
                        choices=[("full", "shapes.json"), ("items", "items.json subset")],
                        default="full",
                        max_length=16,
                    ),
                ),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shape_recipes",
                        to="game_data.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["operation_uid"],
            },
        ),
        migrations.CreateModel(
            name="ResearchUnlockCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                (
                    "parent_kind",
                    models.CharField(
                        choices=[
                            ("milestone", "Milestone"),
                            ("side_quest", "Side quest"),
                            ("line", "Line"),
                        ],
                        max_length=16,
                    ),
                ),
                ("order_index", models.PositiveSmallIntegerField()),
                ("amount", models.PositiveIntegerField(default=1)),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="game_data.researchmilestone",
                    ),
                ),
                (
                    "side_quest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="game_data.researchsidequest",
                    ),
                ),
                (
                    "shape_recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlock_costs",
                        to="game_data.shaperecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="ShapeRecipeLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("layer_index", models.PositiveSmallIntegerField()),
                ("hash_segment", models.CharField(blank=True, default="", max_length=64)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "shape_recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="game_data.shaperecipe",
                    ),
                ),
            ],
            options={
                "ordering": ["layer_index"],
            },
        ),
        migrations.CreateModel(
            name="ShapeQuadrantSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("quadrant_index", models.PositiveSmallIntegerField()),
                ("is_empty_shape", models.BooleanField(default=False)),
                ("is_empty_color", models.BooleanField(default=False)),
                ("hash_token", models.CharField(blank=True, default="", max_length=8)),
                (
                    "fluid_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="game_data.fluidcolor",
                    ),
                ),
                (
                    "shape_component_kind",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="game_data.shapecomponentkind",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="game_data.shaperecipelayer",
                    ),
                ),
            ],
            options={
                "ordering": ["quadrant_index"],
            },
        ),
        migrations.CreateModel(
            name="SimulationSystemEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("source_stable_id", models.CharField(max_length=64)),
                ("simulation_kind_key", models.CharField(db_index=True, max_length=128)),
                ("system_family", models.CharField(blank=True, default="", max_length=32)),
                ("parameter_profile", models.CharField(blank=True, default="", max_length=32)),
                ("clr_type_audit", models.TextField()),
                ("display_name_key", models.CharField(blank=True, default="", max_length=512)),
                ("source_row_index", models.PositiveIntegerField()),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_entries",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationRuntimeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("audit_blob", models.JSONField(default=dict)),
                (
                    "simulation_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runtime_audit",
                        to="game_data.simulationsystementry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationFactoryStub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("factory_type_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "simulation_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory_stub",
                        to="game_data.simulationsystementry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_file", models.CharField(max_length=128)),
                ("source_row_index", models.PositiveIntegerField()),
                ("source_stable_id", models.CharField(blank=True, default="", max_length=64)),
                ("dump_source_type", models.CharField(blank=True, default="", max_length=128)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_objects",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shaperecipe",
            name="source_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shape_recipes",
                to="game_data.sourceobject",
            ),
        ),
        migrations.CreateModel(
            name="ToolbarElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("source_stable_id", models.CharField(max_length=64)),
                ("tree_path", models.CharField(max_length=512, unique=True)),
                (
                    "element_kind",
                    models.CharField(
                        choices=[
                            ("building", "Building placement"),
                            ("island", "Island placement"),
                            ("group", "Group"),
                            ("category", "Category"),
                            ("separator", "Separator"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("section_index", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("source_row_index", models.PositiveIntegerField()),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toolbar_elements",
                        to="game_data.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["tree_path"],
            },
        ),
        migrations.CreateModel(
            name="ToolbarBuildingPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("building_definition_key", models.CharField(max_length=255)),
                ("placer_id", models.CharField(blank=True, default="", max_length=128)),
                ("is_transport_building", models.BooleanField(default=False)),
                ("player_buildable", models.BooleanField(default=True)),
                ("icon_sprite_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "building_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="toolbar_placements",
                        to="game_data.buildingvariant",
                    ),
                ),
                (
                    "toolbar_element",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_placement",
                        to="game_data.toolbarelement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolbarIslandPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("island_group_name", models.CharField(max_length=255)),
                ("placer_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "toolbar_element",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="island_placement",
                        to="game_data.toolbarelement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolbarTreeEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("order_index", models.PositiveSmallIntegerField()),
                (
                    "child_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_edges",
                        to="game_data.toolbarelement",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toolbar_edges",
                        to="game_data.importbatch",
                    ),
                ),
                (
                    "parent_element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_edges",
                        to="game_data.toolbarelement",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="TransportBuildingRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("transport_kind", models.CharField(max_length=128, unique=True)),
                ("transport_category", models.CharField(blank=True, default="", max_length=32)),
                ("display_name_key", models.CharField(blank=True, default="", max_length=512)),
                ("source_row_index", models.PositiveIntegerField()),
                (
                    "building_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transport_registrations",
                        to="game_data.buildingvariant",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_registry",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnknownProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner_model", models.CharField(max_length=64)),
                ("owner_key", models.CharField(max_length=255)),
                ("json_path", models.TextField()),
                ("key", models.CharField(max_length=255)),
                ("value_type", models.CharField(max_length=32)),
                ("value_preview", models.TextField(blank=True, default="")),
                ("value_hash", models.CharField(max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unknown_properties",
                        to="game_data.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuildingPlacementRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("order_index", models.PositiveSmallIntegerField()),
                ("rule_kind", models.CharField(max_length=128)),
                (
                    "building_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_rules",
                        to="game_data.buildinggroup",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building_group", "order_index"), name="uq_placement_rule_order"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BuildingGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("order_index", models.PositiveSmallIntegerField()),
                (
                    "member_resolution",
                    models.CharField(
                        choices=[("embedded", "Embedded"), ("cycle_ref", "Cycle reference")],
                        max_length=16,
                    ),
                ),
                ("internal_variant_name", models.CharField(blank=True, default="", max_length=255)),
                ("cycle_label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "building_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="game_data.buildinggroup",
                    ),
                ),
                (
                    "building_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_memberships",
                        to="game_data.buildingvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building_group", "order_index"), name="uq_group_member_order"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BuildingFootprintTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("order_index", models.PositiveSmallIntegerField()),
                ("x", models.SmallIntegerField(default=0)),
                ("y", models.SmallIntegerField(default=0)),
                ("z", models.SmallIntegerField(default=0)),
                (
                    "building_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footprint_tiles",
                        to="game_data.buildingvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building_variant", "order_index"), name="uq_footprint_tile_order"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BuildingConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("order_index", models.PositiveSmallIntegerField()),
                ("connector_role", models.CharField(max_length=64)),
                ("tile_direction", models.CharField(blank=True, default="", max_length=32)),
                ("io_channel_type", models.CharField(blank=True, default="", max_length=32)),
                ("stand_type", models.CharField(blank=True, default="", max_length=32)),
                ("has_seperators", models.BooleanField(default=False)),
                ("position_x", models.SmallIntegerField(default=0)),
                ("position_y", models.SmallIntegerField(default=0)),
                ("position_z", models.SmallIntegerField(default=0)),
                (
                    "building_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="game_data.buildingvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("building_variant", "order_index"),
                        name="uq_building_connector_order",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="gamecontentasset",
            index=models.Index(
                fields=["content_kind", "content_path"], name="game_data_g_content_1d2f2c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportwarning",
            constraint=models.UniqueConstraint(
                fields=("import_batch", "warning_index"), name="uq_export_warning_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportincompletesection",
            constraint=models.UniqueConstraint(
                fields=("import_batch", "section_code"), name="uq_incomplete_section"
            ),
        ),
        migrations.AddConstraint(
            model_name="clrtyperegistryentry",
            constraint=models.UniqueConstraint(
                fields=("type_name", "assembly_name"), name="uq_clr_type_assembly"
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactchecksum",
            constraint=models.UniqueConstraint(
                fields=("import_batch", "artifact_filename"), name="uq_artifact_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="localizedmessage",
            constraint=models.UniqueConstraint(
                fields=("message_key", "locale_code"), name="uq_localized_message"
            ),
        ),
        migrations.AddConstraint(
            model_name="shaperecipelayer",
            constraint=models.UniqueConstraint(
                fields=("shape_recipe", "layer_index"), name="uq_shape_layer_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="shapequadrantslot",
            constraint=models.UniqueConstraint(
                fields=("layer", "quadrant_index"), name="uq_quadrant_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="simulationsystementry",
            constraint=models.UniqueConstraint(
                fields=("import_batch", "source_row_index"), name="uq_sim_entry_batch_row"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceobject",
            constraint=models.UniqueConstraint(
                fields=("import_batch", "source_file", "source_row_index"),
                name="uq_source_object_row",
            ),
        ),
        migrations.AddConstraint(
            model_name="toolbartreeedge",
            constraint=models.UniqueConstraint(
                fields=("parent_element", "child_element", "order_index"), name="uq_toolbar_edge"
            ),
        ),
        migrations.AddIndex(
            model_name="unknownproperty",
            index=models.Index(
                fields=["import_batch", "owner_model", "owner_key"],
                name="game_data_u_import__074bbc_idx",
            ),
        ),
    ]
