# Generated by Django 5.2.13 on 2026-05-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artifactchecksum",
            options={
                "verbose_name": "artifact checksum",
                "verbose_name_plural": "① Import · Artifact checksums",
            },
        ),
        migrations.AlterModelOptions(
            name="assetmetareference",
            options={
                "verbose_name": "asset meta reference",
                "verbose_name_plural": "② Assets · Meta references",
            },
        ),
        migrations.AlterModelOptions(
            name="buildingconnector",
            options={
                "ordering": ["order_index"],
                "verbose_name": "building connector",
                "verbose_name_plural": "④ Buildings · Connectors",
            },
        ),
        migrations.AlterModelOptions(
            name="buildingfootprinttile",
            options={
                "ordering": ["order_index"],
                "verbose_name": "footprint tile",
                "verbose_name_plural": "④ Buildings · Footprint tiles",
            },
        ),
        migrations.AlterModelOptions(
            name="buildinggroup",
            options={
                "ordering": ["group_key"],
                "verbose_name": "building group",
                "verbose_name_plural": "④ Buildings · Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="buildinggroupmember",
            options={
                "ordering": ["order_index"],
                "verbose_name": "building group member",
                "verbose_name_plural": "④ Buildings · Group members",
            },
        ),
        migrations.AlterModelOptions(
            name="buildinglocalizationoverlay",
            options={
                "verbose_name": "building localization",
                "verbose_name_plural": "④ Buildings · Localization",
            },
        ),
        migrations.AlterModelOptions(
            name="buildingplacementrule",
            options={
                "ordering": ["order_index"],
                "verbose_name": "placement rule",
                "verbose_name_plural": "④ Buildings · Placement rules",
            },
        ),
        migrations.AlterModelOptions(
            name="buildingsimulationsetting",
            options={
                "verbose_name": "building simulation setting",
                "verbose_name_plural": "④ Buildings · Simulation settings",
            },
        ),
        migrations.AlterModelOptions(
            name="buildingvariant",
            options={
                "ordering": ["internal_name"],
                "verbose_name": "building variant",
                "verbose_name_plural": "④ Buildings · Variants",
            },
        ),
        migrations.AlterModelOptions(
            name="clrtyperegistryentry",
            options={
                "verbose_name": "CLR type entry",
                "verbose_name_plural": "⑨ Reflection · CLR types",
            },
        ),
        migrations.AlterModelOptions(
            name="exportincompletesection",
            options={
                "verbose_name": "incomplete section",
                "verbose_name_plural": "① Import · Incomplete sections",
            },
        ),
        migrations.AlterModelOptions(
            name="exportwarning",
            options={
                "ordering": ["warning_index"],
                "verbose_name": "export warning",
                "verbose_name_plural": "① Import · Export warnings",
            },
        ),
        migrations.AlterModelOptions(
            name="fluidcolor",
            options={
                "verbose_name": "fluid color",
                "verbose_name_plural": "③ Shapes · Fluid colors",
            },
        ),
        migrations.AlterModelOptions(
            name="gamecontentasset",
            options={
                "verbose_name": "content asset",
                "verbose_name_plural": "② Assets · Content assets",
            },
        ),
        migrations.AlterModelOptions(
            name="globalbeltspeedpolicy",
            options={
                "verbose_name": "global belt speed policy",
                "verbose_name_plural": "⑥ Simulation · Belt speed policy",
            },
        ),
        migrations.AlterModelOptions(
            name="importbatch",
            options={
                "ordering": ["-imported_at"],
                "verbose_name": "import batch",
                "verbose_name_plural": "① Import · Batches",
            },
        ),
        migrations.AlterModelOptions(
            name="localizationexportstatus",
            options={
                "verbose_name": "localization export status",
                "verbose_name_plural": "⑧ L10n · Export status",
            },
        ),
        migrations.AlterModelOptions(
            name="localizedmessage",
            options={
                "verbose_name": "localized message",
                "verbose_name_plural": "⑧ L10n · Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="researchglobalconfig",
            options={
                "verbose_name": "research global config",
                "verbose_name_plural": "⑤ Research · Global config",
            },
        ),
        migrations.AlterModelOptions(
            name="researchmechanic",
            options={
                "verbose_name": "research mechanic",
                "verbose_name_plural": "⑤ Research · Mechanics",
            },
        ),
        migrations.AlterModelOptions(
            name="researchmilestone",
            options={
                "verbose_name": "research milestone",
                "verbose_name_plural": "⑤ Research · Milestones",
            },
        ),
        migrations.AlterModelOptions(
            name="researchprerequisite",
            options={
                "verbose_name": "research prerequisite",
                "verbose_name_plural": "⑤ Research · Prerequisites",
            },
        ),
        migrations.AlterModelOptions(
            name="researchsidequest",
            options={
                "verbose_name": "research side quest",
                "verbose_name_plural": "⑤ Research · Side quests",
            },
        ),
        migrations.AlterModelOptions(
            name="researchsideupgrade",
            options={
                "verbose_name": "research side upgrade",
                "verbose_name_plural": "⑤ Research · Side upgrades",
            },
        ),
        migrations.AlterModelOptions(
            name="researchunlockcost",
            options={
                "ordering": ["order_index"],
                "verbose_name": "research unlock cost",
                "verbose_name_plural": "⑤ Research · Unlock costs",
            },
        ),
        migrations.AlterModelOptions(
            name="researchupgrade",
            options={
                "verbose_name": "research upgrade",
                "verbose_name_plural": "⑤ Research · Upgrades",
            },
        ),
        migrations.AlterModelOptions(
            name="shapecomponentkind",
            options={
                "verbose_name": "shape component kind",
                "verbose_name_plural": "③ Shapes · Component kinds",
            },
        ),
        migrations.AlterModelOptions(
            name="shapequadrantslot",
            options={
                "ordering": ["quadrant_index"],
                "verbose_name": "shape quadrant slot",
                "verbose_name_plural": "③ Shapes · Quadrant slots",
            },
        ),
        migrations.AlterModelOptions(
            name="shaperecipe",
            options={
                "ordering": ["operation_uid"],
                "verbose_name": "shape recipe",
                "verbose_name_plural": "③ Shapes · Recipes",
            },
        ),
        migrations.AlterModelOptions(
            name="shaperecipelayer",
            options={
                "ordering": ["layer_index"],
                "verbose_name": "shape recipe layer",
                "verbose_name_plural": "③ Shapes · Recipe layers",
            },
        ),
        migrations.AlterModelOptions(
            name="simulationfactorystub",
            options={
                "verbose_name": "simulation factory stub",
                "verbose_name_plural": "⑥ Simulation · Factory stubs",
            },
        ),
        migrations.AlterModelOptions(
            name="simulationruntimeaudit",
            options={
                "verbose_name": "simulation runtime audit",
                "verbose_name_plural": "⑥ Simulation · Runtime audit",
            },
        ),
        migrations.AlterModelOptions(
            name="simulationsystementry",
            options={
                "verbose_name": "simulation system entry",
                "verbose_name_plural": "⑥ Simulation · System entries",
            },
        ),
        migrations.AlterModelOptions(
            name="sourceobject",
            options={
                "verbose_name": "source object",
                "verbose_name_plural": "① Import · Source objects",
            },
        ),
        migrations.AlterModelOptions(
            name="toolbarbuildingplacement",
            options={
                "verbose_name": "toolbar building placement",
                "verbose_name_plural": "⑦ Toolbar · Building placements",
            },
        ),
        migrations.AlterModelOptions(
            name="toolbarelement",
            options={
                "ordering": ["tree_path"],
                "verbose_name": "toolbar element",
                "verbose_name_plural": "⑦ Toolbar · Elements",
            },
        ),
        migrations.AlterModelOptions(
            name="toolbarislandplacement",
            options={
                "verbose_name": "toolbar island placement",
                "verbose_name_plural": "⑦ Toolbar · Island placements",
            },
        ),
        migrations.AlterModelOptions(
            name="toolbartreeedge",
            options={
                "ordering": ["order_index"],
                "verbose_name": "toolbar tree edge",
                "verbose_name_plural": "⑦ Toolbar · Tree edges",
            },
        ),
        migrations.AlterModelOptions(
            name="transportbuildingregistry",
            options={
                "verbose_name": "transport registry",
                "verbose_name_plural": "④ Buildings · Transport registry",
            },
        ),
        migrations.AlterModelOptions(
            name="unknownproperty",
            options={
                "verbose_name": "unknown property",
                "verbose_name_plural": "① Import · Unknown properties",
            },
        ),
        migrations.RemoveField(
            model_name="researchmilestone",
            name="description",
        ),
        migrations.RemoveField(
            model_name="researchmilestone",
            name="title",
        ),
        migrations.RemoveField(
            model_name="researchsidequest",
            name="title",
        ),
        migrations.CreateModel(
            name="LazyLocalizedTextRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                (
                    "message_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=512),
                ),
                ("lazy_text_type", models.CharField(blank=True, default="", max_length=128)),
                (
                    "placeholder_resolver_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("is_cycle_reference", models.BooleanField(default=False)),
                ("cycle_reference", models.CharField(blank=True, default="", max_length=255)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lazy_localized_text_refs",
                        to="game_data.importbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "lazy localized text",
                "verbose_name_plural": "⑧ L10n · Lazy text refs",
            },
        ),
        migrations.AddField(
            model_name="researchmilestone",
            name="description_lazy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="milestone_descriptions",
                to="game_data.lazylocalizedtextref",
            ),
        ),
        migrations.AddField(
            model_name="researchmilestone",
            name="title_lazy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="milestone_titles",
                to="game_data.lazylocalizedtextref",
            ),
        ),
        migrations.AddField(
            model_name="researchsidequest",
            name="description_lazy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="side_quest_descriptions",
                to="game_data.lazylocalizedtextref",
            ),
        ),
        migrations.AddField(
            model_name="researchsidequest",
            name="title_lazy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="side_quest_titles",
                to="game_data.lazylocalizedtextref",
            ),
        ),
        migrations.CreateModel(
            name="LazyLocalizedPlaceholderReplacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("replacement_key", models.CharField(max_length=255)),
                ("value_kind", models.CharField(blank=True, default="", max_length=64)),
                ("nested_message_key", models.CharField(blank=True, default="", max_length=512)),
                ("value_preview", models.TextField(blank=True, default="")),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "lazy_text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placeholder_replacements",
                        to="game_data.lazylocalizedtextref",
                    ),
                ),
            ],
            options={
                "verbose_name": "lazy localized placeholder",
                "verbose_name_plural": "⑧ L10n · Placeholder replacements",
                "ordering": ["order_index", "replacement_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lazy_text", "replacement_key"), name="uq_lazy_placeholder_key"
                    )
                ],
            },
        ),
    ]
