# Generated by Django 5.2.13 on 2026-05-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_data", "0020_prune_subtable_taxonomy_sections"),
        ("game_data", "0019_simulation_runtime_audit_issue_unique"),
    ]

    operations = []
