# Generated by Django 5.2.13 on 2026-05-22 18:03

import django.db.models.deletion
from django.db import migrations, models


def drop_toolbar_elements_without_tree_node(apps, schema_editor) -> None:
    """Remove legacy rows before enforcing non-null tree_node (importer always sets FK)."""

    Element = apps.get_model("game_data", "ToolbarElement")
    Element.objects.filter(tree_node__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game_data", "0024_shape_recipe_pair_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artifactchecksum",
            options={
                "verbose_name": "source file checksum",
                "verbose_name_plural": "① Import · Source file checksums",
            },
        ),
        migrations.AlterModelOptions(
            name="importbatch",
            options={
                "ordering": ["-imported_at"],
                "verbose_name": "import run",
                "verbose_name_plural": "① Import · Runs",
            },
        ),
        migrations.AlterModelOptions(
            name="unknownproperty",
            options={
                "verbose_name": "ignored field",
                "verbose_name_plural": "① Import · Ignored fields",
            },
        ),
        migrations.RenameIndex(
            model_name="gamedatareference",
            new_name="game_data_g_import__b78c7f_idx",
            old_name="gd_ref_batch_kind_res",
        ),
        migrations.RunPython(
            drop_toolbar_elements_without_tree_node,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="toolbarelement",
            name="tree_node",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toolbar_element",
                to="game_data.toolbartreenode",
            ),
        ),
    ]
