# Generated by Django 5.2.13 on 2026-05-24 23:59

from __future__ import annotations

from decimal import Decimal

from django.db import migrations, models


def seed_mining_extraction_rules(apps, schema_editor) -> None:
    Rule = apps.get_model("game_data", "MiningExtractionRule")
    rows = (
        {
            "resource_kind": "shape",
            "transport_kind": "shape_belt",
            "mini_unit_output_per_min": Decimal("30.0000"),
            "output_unit": "shapes_per_min",
            "base_mini_units_per_miner": 4,
            "mini_units_per_extension": 4,
            "max_extension_count": 3,
            "source_kind": "CANON_MANUAL",
            "source_note": (
                "Queryable mirror of L1 CANON: "
                "documents/game_rules/shapez2_asteroid_space_transport_throughput.md"
            ),
            "is_active": True,
        },
        {
            "resource_kind": "fluid",
            "transport_kind": "fluid_pipe",
            "mini_unit_output_per_min": Decimal("300.0000"),
            "output_unit": "liters_per_min",
            "base_mini_units_per_miner": 4,
            "mini_units_per_extension": 4,
            "max_extension_count": 3,
            "source_kind": "CANON_MANUAL",
            "source_note": (
                "Queryable mirror of L1 CANON: "
                "documents/game_rules/shapez2_asteroid_space_transport_throughput.md"
            ),
            "is_active": True,
        },
    )
    for row in rows:
        resource_kind = row["resource_kind"]
        Rule.objects.update_or_create(
            resource_kind=resource_kind,
            is_active=True,
            defaults={
                "transport_kind": row["transport_kind"],
                "mini_unit_output_per_min": row["mini_unit_output_per_min"],
                "output_unit": row["output_unit"],
                "base_mini_units_per_miner": row["base_mini_units_per_miner"],
                "mini_units_per_extension": row["mini_units_per_extension"],
                "max_extension_count": row["max_extension_count"],
                "source_kind": row["source_kind"],
                "source_note": row["source_note"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("game_data", "0025_alter_artifactchecksum_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiningExtractionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource_kind",
                    models.CharField(
                        choices=[("shape", "Shape"), ("fluid", "Fluid")], max_length=16
                    ),
                ),
                ("transport_kind", models.CharField(max_length=64)),
                ("mini_unit_output_per_min", models.DecimalField(decimal_places=4, max_digits=12)),
                ("output_unit", models.CharField(max_length=64)),
                ("base_mini_units_per_miner", models.PositiveSmallIntegerField(default=4)),
                ("mini_units_per_extension", models.PositiveSmallIntegerField(default=4)),
                ("max_extension_count", models.PositiveSmallIntegerField(default=3)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("CANON_MANUAL", "CANON manual")],
                        default="CANON_MANUAL",
                        max_length=32,
                    ),
                ),
                ("source_note", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "mining extraction rule",
                "verbose_name_plural": "⑦ Mining · Extraction rules",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("resource_kind",),
                        name="unique_active_mining_extraction_rule_per_resource",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_mining_extraction_rules, migrations.RunPython.noop),
    ]
