# Generated by Django 5.2.13 on 2026-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_data", "0029_evtc_tier1_shapez2_miner_belt_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="buildings_per_regular_belt",
            field=models.PositiveSmallIntegerField(
                help_text="Mini units per inner belt (tier-1: 4 → 120 shapes/min)."
            ),
        ),
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="lanes_per_line",
            field=models.PositiveSmallIntegerField(
                help_text="Inner belts per miner line (tier-1: 12; line sizing 480/min)."
            ),
        ),
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="lines_per_space_belt",
            field=models.PositiveSmallIntegerField(
                help_text="Lines per Space Belt (tier-1: 12 → 5760 shapes/min belt)."
            ),
        ),
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="miner_full_output_multiplier",
            field=models.PositiveSmallIntegerField(
                help_text="Expander multiplier on mini miner (tier-1: 16 → 480 shapes/min line)."
            ),
        ),
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="mini_unit_output_per_min",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Mini miner base extraction (tier-1 CANON: 30 shapes/min).",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="space_belt_full_belt_count",
            field=models.PositiveSmallIntegerField(
                help_text="Inner-belt equivalents at saturated wiki cap (48 × 120/min → 5760/min)."
            ),
        ),
    ]
