# Generated by Django 5.2.13 on 2026-05-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "game_data",
            "0030_alter_exteriorshapetransportcapacity_buildings_per_regular_belt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="buildings_per_regular_belt",
            field=models.PositiveSmallIntegerField(
                help_text=(
                    "Mini units per inner belt group "
                    "(tier-1 CANON: 4 → 120 shapes/min inner belt)."
                )
            ),
        ),
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="lanes_per_line",
            field=models.PositiveSmallIntegerField(
                help_text=(
                    "Inner belts exporting outside one miner "
                    "(tier-1 CANON: 12; sizing uses 480/min line)."
                )
            ),
        ),
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="lines_per_space_belt",
            field=models.PositiveSmallIntegerField(
                help_text=(
                    "Exterior lines per Space Belt building "
                    "(tier-1 CANON: 12 → 5760 shapes/min belt)."
                )
            ),
        ),
        migrations.AlterField(
            model_name="exteriorshapetransportcapacity",
            name="miner_full_output_multiplier",
            field=models.PositiveSmallIntegerField(
                help_text=(
                    "Expander full-setup multiplier on mini miner "
                    "(tier-1 CANON: 16 → 480 shapes/min line)."
                )
            ),
        ),
    ]
