# Generated by Django 5.2.13 on 2026-06-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "game_data",
            "0031_alter_exteriorshapetransportcapacity_buildings_per_regular_belt_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceTransportLayoutRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_id", models.CharField(max_length=255, unique=True)),
                ("tile_id", models.CharField(max_length=128, unique=True)),
                (
                    "transport_kind",
                    models.CharField(
                        choices=[("space_belt", "Space belt"), ("space_pipe", "Space pipe")],
                        max_length=32,
                    ),
                ),
                ("group_id", models.CharField(max_length=64)),
                ("layout_suffix", models.CharField(max_length=64)),
                ("simulation_system_key", models.TextField(blank=True, default="")),
                (
                    "simulation_family",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conveyor", "Conveyor"),
                            ("merger", "Merger"),
                            ("splitter", "Splitter"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("routing_allowed", models.BooleanField(default=True)),
                ("canonical_rotation", models.PositiveSmallIntegerField(default=0)),
                (
                    "allowed_rotations",
                    models.CharField(
                        default="0,1,2,3",
                        help_text="Comma-separated rotation indices (East=0, clockwise).",
                        max_length=16,
                    ),
                ),
                ("has_io_signature", models.BooleanField(default=False)),
                (
                    "input_mask_eswn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ESWN mask as 4-char 0/1 string when curated IO exists.",
                        max_length=4,
                    ),
                ),
                ("output_mask_eswn", models.CharField(blank=True, default="", max_length=4)),
                ("source_row_index", models.PositiveIntegerField(default=0)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_transport_layouts",
                        to="game_data.importbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "space transport layout",
                "verbose_name_plural": "⑧ EVTC · Space transport layouts",
                "ordering": ["tile_id"],
            },
        ),
    ]
