# Generated by Django 5.2.13 on 2026-05-03 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shapez_solver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatternFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "signature",
                    models.CharField(db_index=True, max_length=16, verbose_name="시그니처"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("allow_rotation", models.BooleanField(default=True, verbose_name="회전 허용")),
                ("allow_reflection", models.BooleanField(default=False, verbose_name="반사 허용")),
                ("priority", models.IntegerField(default=100, verbose_name="우선순위")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="활성"),
                ),
                (
                    "schema_version",
                    models.PositiveIntegerField(default=1, verbose_name="스키마 버전"),
                ),
            ],
            options={
                "verbose_name": "패턴 패밀리",
                "verbose_name_plural": "패턴 패밀리",
                "ordering": ("priority", "code"),
                "indexes": [
                    models.Index(fields=["code"], name="shapez_solv_code_0cad49_idx"),
                    models.Index(fields=["signature"], name="shapez_solv_signatu_80f3a2_idx"),
                    models.Index(
                        fields=["is_active", "priority"], name="shapez_solv_is_acti_0ccc7b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MacroRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                ("strategy_code", models.SlugField(verbose_name="Python strategy 코드")),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "estimated_operation_cost",
                    models.PositiveIntegerField(default=1, verbose_name="예상 작업 비용"),
                ),
                (
                    "estimated_stage_cost",
                    models.PositiveIntegerField(default=1, verbose_name="예상 단계 비용"),
                ),
                (
                    "estimated_waste_cost",
                    models.PositiveIntegerField(default=0, verbose_name="예상 폐기 비용"),
                ),
                ("priority", models.IntegerField(default=100, verbose_name="우선순위")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="활성"),
                ),
                (
                    "schema_version",
                    models.PositiveIntegerField(default=1, verbose_name="스키마 버전"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macro_recipes",
                        to="shapez_solver.patternfamily",
                        verbose_name="패턴 패밀리",
                    ),
                ),
            ],
            options={
                "verbose_name": "매크로 레시피",
                "verbose_name_plural": "매크로 레시피",
                "ordering": ("priority", "code"),
            },
        ),
        migrations.CreateModel(
            name="PatternTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("template", models.CharField(max_length=32, verbose_name="템플릿")),
                (
                    "normalized_template",
                    models.CharField(db_index=True, max_length=32, verbose_name="정규화 템플릿"),
                ),
                ("display_name", models.CharField(max_length=100, verbose_name="표시 이름")),
                (
                    "min_distinct_parts",
                    models.PositiveSmallIntegerField(default=1, verbose_name="최소 파트 수"),
                ),
                (
                    "max_distinct_parts",
                    models.PositiveSmallIntegerField(default=4, verbose_name="최대 파트 수"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="활성"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="shapez_solver.patternfamily",
                        verbose_name="패턴 패밀리",
                    ),
                ),
            ],
            options={
                "verbose_name": "패턴 템플릿",
                "verbose_name_plural": "패턴 템플릿",
                "ordering": ("family__priority", "normalized_template"),
            },
        ),
        migrations.CreateModel(
            name="MacroRecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("step_index", models.PositiveIntegerField(verbose_name="단계 번호")),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("cutter", "CUTTER"),
                            ("cutter_full", "CUTTER_FULL"),
                            ("half_destroyer", "HALF_DESTROYER"),
                            ("splitter", "SPLITTER"),
                            ("swapper", "SWAPPER"),
                            ("rotate_cw", "ROTATE_CW"),
                            ("rotate_ccw", "ROTATE_CCW"),
                            ("rotate_180", "ROTATE_180"),
                            ("stacker", "STACKER"),
                            ("painter", "PAINTER"),
                            ("color_mixer", "COLOR_MIXER"),
                            ("pin_pusher", "PIN_PUSHER"),
                            ("crystal_generator", "CRYSTAL_GENERATOR"),
                        ],
                        max_length=32,
                        verbose_name="작업",
                    ),
                ),
                ("input_slots", models.JSONField(default=list, verbose_name="입력 슬롯")),
                ("output_slots", models.JSONField(default=list, verbose_name="출력 슬롯")),
                ("note", models.TextField(blank=True, verbose_name="메모")),
                (
                    "macro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="shapez_solver.macrorecipe",
                        verbose_name="매크로 레시피",
                    ),
                ),
            ],
            options={
                "verbose_name": "매크로 레시피 단계",
                "verbose_name_plural": "매크로 레시피 단계",
                "ordering": ("macro", "step_index"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("macro", "step_index"), name="unique_macro_recipe_step_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PatternExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "input_shape_code",
                    models.CharField(max_length=64, verbose_name="입력 shape code"),
                ),
                (
                    "expected_signature",
                    models.CharField(max_length=16, verbose_name="예상 시그니처"),
                ),
                ("note", models.TextField(blank=True, verbose_name="메모")),
                (
                    "expected_macro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examples",
                        to="shapez_solver.macrorecipe",
                        verbose_name="예상 매크로",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="shapez_solver.patternfamily",
                        verbose_name="패턴 패밀리",
                    ),
                ),
            ],
            options={
                "verbose_name": "패턴 예시",
                "verbose_name_plural": "패턴 예시",
                "ordering": ("family__priority", "input_shape_code"),
                "indexes": [
                    models.Index(
                        fields=["input_shape_code"], name="shapez_solv_input_s_4911f8_idx"
                    ),
                    models.Index(
                        fields=["expected_signature"], name="shapez_solv_expecte_b7d382_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="macrorecipe",
            index=models.Index(fields=["code"], name="shapez_solv_code_6786c7_idx"),
        ),
        migrations.AddIndex(
            model_name="macrorecipe",
            index=models.Index(fields=["strategy_code"], name="shapez_solv_strateg_28abf6_idx"),
        ),
        migrations.AddIndex(
            model_name="macrorecipe",
            index=models.Index(
                fields=["is_active", "priority"], name="shapez_solv_is_acti_1c1e96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patterntemplate",
            index=models.Index(
                fields=["normalized_template"], name="shapez_solv_normali_e9de1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patterntemplate",
            index=models.Index(fields=["is_active"], name="shapez_solv_is_acti_05eaef_idx"),
        ),
    ]
