# Generated by Django 5.2.13 on 2026-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shapez_solver", "0002_patternfamily_macrorecipe_patterntemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="macrorecipe",
            name="graph_document",
            field=models.JSONField(
                blank=True,
                help_text=(
                    "Recipe Graph Editor용 노드·엣지·좌표(JSON). " "null이면 스텝 테이블만 사용."
                ),
                null=True,
                verbose_name="레시피 그래프 문서",
            ),
        ),
    ]
