# Generated by Django 5.2.13 on 2026-05-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shapez_solver", "0007_macrorecipestep_operation_merge"),
    ]

    operations = [
        migrations.CreateModel(
            name="MacroRecipeCompiledBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "graph_shape_id",
                    models.CharField(max_length=128, verbose_name="그래프 shape 노드 id"),
                ),
                (
                    "pattern_signature",
                    models.CharField(max_length=16, verbose_name="패턴 시그니처"),
                ),
                (
                    "boundary",
                    models.CharField(
                        choices=[("start", "start"), ("end", "end")],
                        max_length=8,
                        verbose_name="경계",
                    ),
                ),
                (
                    "macro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiled_boundaries",
                        to="shapez_solver.macrorecipe",
                        verbose_name="매크로 레시피",
                    ),
                ),
            ],
            options={
                "verbose_name": "매크로 컴파일 경계",
                "verbose_name_plural": "매크로 컴파일 경계",
                "indexes": [
                    models.Index(
                        fields=["macro", "boundary", "pattern_signature"],
                        name="shapez_solv_macro_i_af4359_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("macro", "graph_shape_id"),
                        name="unique_macro_compiled_boundary_shape_id",
                    )
                ],
            },
        ),
    ]
