# Generated by Django 5.2.13 on 2026-05-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shapez_solver", "0008_macrorecipecompiledboundary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatternExample",
        ),
        migrations.DeleteModel(
            name="MacroRecipeCompiledBoundary",
        ),
        migrations.DeleteModel(
            name="MacroRecipeStep",
        ),
        migrations.DeleteModel(
            name="MacroRecipe",
        ),
        migrations.DeleteModel(
            name="PatternTemplate",
        ),
        migrations.DeleteModel(
            name="PatternFamily",
        ),
    ]
