"""Infer JSON type shapes for documents/game_data/*.json (values omitted)."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

SOURCE_DIR = Path(__file__).resolve().parents[1] / "documents" / "game_data"
MAX_ARRAY_SAMPLES = 8
MAX_OBJECT_KEYS_SAMPLE = 200
MAX_DEPTH = 32


def merge_types(a: str, b: str) -> str:
    if a == b or a == "null" or b == "null":
        return a if a != "null" else b
    parts = sorted(set(a.split(" | ")) | set(b.split(" | ")))
    return " | ".join(parts)


def infer(value: object, depth: int = 0) -> str:
    if depth > MAX_DEPTH:
        return "…"
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        if not value:
            return "array<empty>"
        t = "array<empty>"
        for item in value[:MAX_ARRAY_SAMPLES]:
            t = merge_types(t, infer(item, depth + 1))
        if len(value) > MAX_ARRAY_SAMPLES:
            t = f"{t} /* len≥{len(value)}, sampled {MAX_ARRAY_SAMPLES} */"
        return t
    if isinstance(value, dict):
        if not value:
            return "object{}"
        lines: list[str] = []
        for k in sorted(value.keys())[:MAX_OBJECT_KEYS_SAMPLE]:
            lines.append(f'  "{k}": {infer(value[k], depth + 1)};')
        extra = len(value) - MAX_OBJECT_KEYS_SAMPLE
        if extra > 0:
            lines.append(f"  /* … +{extra} more keys (not listed) */")
        return "object {\n" + "\n".join(lines) + "\n}"
    return type(value).__name__


def root_kind(data: object) -> str:
    if isinstance(data, list):
        return f"array[{len(data)}]"
    if isinstance(data, dict):
        return f"object[{len(data)} keys]"
    return type(data).__name__


def row_envelope_keys(rows: list[object]) -> Counter[str]:
    c: Counter[str] = Counter()
    for row in rows[:MAX_ARRAY_SAMPLES]:
        if isinstance(row, dict):
            c.update(row.keys())
    return c


def main() -> int:
    files = sorted(SOURCE_DIR.glob("*.json"))
    out_lines: list[str] = []
    out_lines.append("# documents/game_data JSON — inferred type shapes")
    out_lines.append("")
    out_lines.append("Auto-generated by `scripts/_infer_game_data_json_schema.py`.")
    out_lines.append('Notation: `object { "key": type; }`, unions as `a | b`.')
    out_lines.append("Large arrays/objects are **sampled** (not exhaustive).")
    out_lines.append("")

    for path in files:
        text = path.read_text(encoding="utf-8-sig")
        data = json.loads(text)
        out_lines.append(f"## `{path.name}`")
        out_lines.append("")
        out_lines.append(f"- **Root**: `{root_kind(data)}`")
        out_lines.append(f"- **Size**: {path.stat().st_size:,} bytes")
        out_lines.append("")

        if isinstance(data, list) and data and isinstance(data[0], dict):
            keys = row_envelope_keys(data)
            out_lines.append("### Row envelope (keys seen in first rows)")
            out_lines.append("")
            sample_n = min(MAX_ARRAY_SAMPLES, len(data))
            for key, count in keys.most_common():
                req = "required*" if count >= min(MAX_ARRAY_SAMPLES, len(data)) else "optional"
                out_lines.append(f"- `{key}` — {req} ({count}/{sample_n} samples)")
            out_lines.append("")

        if isinstance(data, list) and data:
            sample = data[0]
            out_lines.append("### First element shape")
            out_lines.append("")
            out_lines.append("```")
            out_lines.append(infer(sample))
            out_lines.append("```")
            out_lines.append("")

            if len(data) > 1:
                merged = infer(sample)
                for item in data[1:MAX_ARRAY_SAMPLES]:
                    merged = merge_types(merged, infer(item))
                out_lines.append("### Merged shape (first N elements)")
                out_lines.append("")
                out_lines.append("```")
                out_lines.append(merged)
                out_lines.append("```")
                out_lines.append("")
        else:
            out_lines.append("### Full root shape")
            out_lines.append("")
            out_lines.append("```")
            out_lines.append(infer(data))
            out_lines.append("```")
            out_lines.append("")

    doc_path = Path(__file__).resolve().parents[1] / "docs" / "domain" / "game_data_json_schema.md"
    doc_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text("\n".join(out_lines), encoding="utf-8")
    print(doc_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
