# Generated by Django 5.2.13 on 2026-05-07 18:28

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def seed_status_kinds(apps, schema_editor) -> None:
    Kind = apps.get_model("shapez_asteroid", "AsteroidCellStatusKind")
    for slug, label in (
        ("void", "void"),
        ("shape_asteroid", "shape asteroid"),
        ("fluid_asteroid", "fluid asteroid"),
        ("shape_extractor", "shape extractor"),
        ("fluid_extractor", "fluid extractor"),
    ):
        Kind.objects.get_or_create(slug=slug, defaults={"label": label})


def unseed_status_kinds(apps, schema_editor) -> None:
    MapCell = apps.get_model("shapez_asteroid", "AsteroidMapCell")
    MapCell.objects.all().delete()
    Kind = apps.get_model("shapez_asteroid", "AsteroidCellStatusKind")
    Kind.objects.filter(
        slug__in=(
            "void",
            "shape_asteroid",
            "fluid_asteroid",
            "shape_extractor",
            "fluid_extractor",
        )
    ).delete()


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("shapez_asteroid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsteroidCellStatusKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="AsteroidMapCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cells",
                        to="shapez_asteroid.asteroidcellstatuskind",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["x", "y"], name="shapez_aste_x_3ba722_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("x", "y"), name="shapez_asteroid_mapcell_xy_uniq"
                    ),
                    models.CheckConstraint(
                        condition=~Q(x=0),
                        name="shapez_asteroid_mapcell_x_nonzero",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_status_kinds, unseed_status_kinds),
    ]
