"""Re-export all game_data ORM models (stable ``django_apps.game_data.models`` import path)."""

# ruff: noqa: E501

from django_apps.game_data.models.assets import AssetMetaReference, GameContentAsset
from django_apps.game_data.models.buildings import (
    BuildingConnector,
    BuildingFootprintTile,
    BuildingGroup,
    BuildingGroupMember,
    BuildingLocalizationOverlay,
    BuildingPlacementRule,
    BuildingSimulationSetting,
    BuildingVariant,
    TransportBuildingRegistry,
)
from django_apps.game_data.models.exterior_transport_capacity import (
    ExteriorFluidTransportCapacity,
    ExteriorShapeTransportCapacity,
)
from django_apps.game_data.models.import_meta import (
    ArtifactChecksum,
    ExportIncompleteSection,
    ExportWarning,
    ImportBatch,
    LocalizationExportStatus,
    SourceObject,
    UnknownProperty,
)
from django_apps.game_data.models.l10n import (
    LazyLocalizedPlaceholderReplacement,
    LazyLocalizedTextRef,
    LocalizedMessage,
)
from django_apps.game_data.models.mining import MiningExtractionRule
from django_apps.game_data.models.references import GameDataReference
from django_apps.game_data.models.reflection import ClrTypeRegistryEntry
from django_apps.game_data.models.research import (
    ResearchGlobalConfig,
    ResearchMechanic,
    ResearchMilestone,
    ResearchPrerequisite,
    ResearchSideQuest,
    ResearchSideUpgrade,
    ResearchUnlockCost,
    ResearchUpgrade,
)
from django_apps.game_data.models.shapes import (
    FluidColor,
    ShapeComponentKind,
    ShapeQuadrantSlot,
    ShapeRecipe,
    ShapeRecipeLayer,
    ShapeRecipeSourceAppearance,
)
from django_apps.game_data.models.simulation import (
    ConnectableSimulation,
    GlobalBeltSpeedPolicy,
    SimulationBuffableSpeed,
    SimulationChunkBounds,
    SimulationClrProvenance,
    SimulationConnector,
    SimulationConnectorProperty,
    SimulationLaneDefinition,
    SimulationLaneRuntimeState,
    SimulationMultipleBeltSpeed,
    SimulationProfile,
    SimulationRuntimeAuditIssue,
    SimulationStateType,
    SimulationSystem,
    SimulationSystemParameterKey,
    SimulationSystemParameterOccurrence,
    SimulationTileBounds,
    SimulationType,
)
from django_apps.game_data.models.space_transport_layout import SpaceTransportLayoutRegistry
from django_apps.game_data.models.taxonomy import GameDataNamespace, GameDataSection
from django_apps.game_data.models.toolbar import (
    ToolbarBuildingPlacement,
    ToolbarElement,
    ToolbarIslandPlacement,
    ToolbarNodeKind,
    ToolbarTreeNode,
)

__all__ = [
    "ArtifactChecksum",
    "AssetMetaReference",
    "BuildingConnector",
    "BuildingFootprintTile",
    "BuildingGroup",
    "BuildingGroupMember",
    "BuildingLocalizationOverlay",
    "BuildingPlacementRule",
    "BuildingSimulationSetting",
    "BuildingVariant",
    "ClrTypeRegistryEntry",
    "ConnectableSimulation",
    "ExportIncompleteSection",
    "ExportWarning",
    "ExteriorFluidTransportCapacity",
    "ExteriorShapeTransportCapacity",
    "FluidColor",
    "GameContentAsset",
    "GlobalBeltSpeedPolicy",
    "ImportBatch",
    "LazyLocalizedPlaceholderReplacement",
    "LazyLocalizedTextRef",
    "LocalizationExportStatus",
    "LocalizedMessage",
    "MiningExtractionRule",
    "ResearchGlobalConfig",
    "ResearchMechanic",
    "ResearchMilestone",
    "ResearchPrerequisite",
    "ResearchSideQuest",
    "ResearchSideUpgrade",
    "ResearchUnlockCost",
    "ResearchUpgrade",
    "ShapeComponentKind",
    "ShapeQuadrantSlot",
    "ShapeRecipe",
    "ShapeRecipeLayer",
    "ShapeRecipeSourceAppearance",
    "SimulationBuffableSpeed",
    "SimulationChunkBounds",
    "SimulationClrProvenance",
    "SimulationConnector",
    "SimulationConnectorProperty",
    "SimulationLaneDefinition",
    "SimulationLaneRuntimeState",
    "SimulationMultipleBeltSpeed",
    "SimulationProfile",
    "GameDataNamespace",
    "GameDataReference",
    "GameDataSection",
    "SimulationRuntimeAuditIssue",
    "SimulationStateType",
    "SimulationSystem",
    "SimulationSystemParameterKey",
    "SimulationSystemParameterOccurrence",
    "SimulationTileBounds",
    "SimulationType",
    "SpaceTransportLayoutRegistry",
    "SourceObject",
    "ToolbarBuildingPlacement",
    "ToolbarElement",
    "ToolbarIslandPlacement",
    "ToolbarNodeKind",
    "ToolbarTreeNode",
    "TransportBuildingRegistry",
    "UnknownProperty",
]
